const DUTCH_LIBRARY = {
    words: {
        easy: [
            // Body parts
            {nl:"Hoofd", en:"Head", ph:"Hohft"}, {nl:"Oog", en:"Eye", ph:"Ohg"},
            {nl:"Neus", en:"Nose", ph:"Nurs"}, {nl:"Mond", en:"Mouth", ph:"Mont"},
            {nl:"Oor", en:"Ear", ph:"Ohr"}, {nl:"Hand", en:"Hand", ph:"Hant"},
            {nl:"Voet", en:"Foot", ph:"Voot"}, {nl:"Arm", en:"Arm", ph:"Arm"},
            {nl:"Been", en:"Leg", ph:"Bayn"}, {nl:"Vinger", en:"Finger", ph:"Ving-er"},
            {nl:"Rug", en:"Back", ph:"Ruhg"}, {nl:"Nek", en:"Neck", ph:"Nek"},
            {nl:"Haar", en:"Hair", ph:"Har"}, {nl:"Gezicht", en:"Face", ph:"Ghe-zikht"},
            {nl:"Tand", en:"Tooth", ph:"Tant"}, {nl:"Tong", en:"Tongue", ph:"Tong"},
            // Colors
            {nl:"Rood", en:"Red", ph:"Roht"}, {nl:"Blauw", en:"Blue", ph:"Blow"},
            {nl:"Groen", en:"Green", ph:"Groon"}, {nl:"Geel", en:"Yellow", ph:"Gayl"},
            {nl:"Wit", en:"White", ph:"Wit"}, {nl:"Zwart", en:"Black", ph:"Zwart"},
            {nl:"Roze", en:"Pink", ph:"Roh-ze"}, {nl:"Oranje", en:"Orange", ph:"Oh-ran-ye"},
            {nl:"Paars", en:"Purple", ph:"Pars"}, {nl:"Grijs", en:"Grey", ph:"Ghrays"},
            {nl:"Bruin", en:"Brown", ph:"Brown"},
            // More Colors
            {nl:"Beige", en:"Beige", ph:"Bezh"}, {nl:"Turquoise", en:"Turquoise", ph:"Tur-kwaz"},
            {nl:"Goud", en:"Gold", ph:"Ghowt"}, {nl:"Zilver", en:"Silver", ph:"Zil-ver"},
            {nl:"Bordeaux", en:"Burgundy", ph:"Bor-doh"}, {nl:"Lila", en:"Lilac", ph:"Lee-la"},
            {nl:"Crème", en:"Cream", ph:"Krehm"}, {nl:"Magenta", en:"Magenta", ph:"Ma-ghen-ta"},
            {nl:"Koraal", en:"Coral", ph:"Ko-rahl"}, {nl:"Indigo", en:"Indigo", ph:"In-dee-go"},
            // Numbers 1–10
            {nl:"Één", en:"One", ph:"Ayn"}, {nl:"Twee", en:"Two", ph:"Tway"},
            {nl:"Drie", en:"Three", ph:"Dree"}, {nl:"Vier", en:"Four", ph:"Veer"},
            {nl:"Vijf", en:"Five", ph:"Vayf"}, {nl:"Zes", en:"Six", ph:"Zes"},
            {nl:"Zeven", en:"Seven", ph:"Zay-ven"}, {nl:"Acht", en:"Eight", ph:"Akht"},
            {nl:"Negen", en:"Nine", ph:"Nay-ghen"}, {nl:"Tien", en:"Ten", ph:"Teen"},
            // Numbers 11–20
            {nl:"Elf", en:"Eleven", ph:"Elf"}, {nl:"Twaalf", en:"Twelve", ph:"Twalf"},
            {nl:"Dertien", en:"Thirteen", ph:"Der-teen"}, {nl:"Veertien", en:"Fourteen", ph:"Vayr-teen"},
            {nl:"Vijftien", en:"Fifteen", ph:"Vayf-teen"}, {nl:"Zestien", en:"Sixteen", ph:"Zes-teen"},
            {nl:"Zeventien", en:"Seventeen", ph:"Zay-ven-teen"}, {nl:"Achttien", en:"Eighteen", ph:"Akh-teen"},
            {nl:"Negentien", en:"Nineteen", ph:"Nay-ghen-teen"}, {nl:"Twintig", en:"Twenty", ph:"Twin-tikh"},
            // Numbers — Tens
            {nl:"Dertig", en:"Thirty", ph:"Der-tikh"}, {nl:"Veertig", en:"Forty", ph:"Vayr-tikh"},
            {nl:"Vijftig", en:"Fifty", ph:"Vayf-tikh"}, {nl:"Zestig", en:"Sixty", ph:"Zes-tikh"},
            {nl:"Zeventig", en:"Seventy", ph:"Zay-ven-tikh"}, {nl:"Tachtig", en:"Eighty", ph:"Takh-tikh"},
            {nl:"Negentig", en:"Ninety", ph:"Nay-ghen-tikh"}, {nl:"Honderd", en:"Hundred", ph:"Hon-dert"}, {nl:"Duizend", en:"Thousand", ph:"Dow-zent"},
            // Family
            {nl:"Moeder", en:"Mother", ph:"Moo-der"}, {nl:"Vader", en:"Father", ph:"Fah-der"},
            {nl:"Broer", en:"Brother", ph:"Broor"}, {nl:"Zus", en:"Sister", ph:"Zuhs"},
            {nl:"Zoon", en:"Son", ph:"Zohn"}, {nl:"Dochter", en:"Daughter", ph:"Dokh-ter"},
            {nl:"Opa", en:"Grandfather", ph:"Oh-pa"}, {nl:"Oma", en:"Grandmother", ph:"Oh-ma"},
            {nl:"Oom", en:"Uncle", ph:"Ohm"}, {nl:"Tante", en:"Aunt", ph:"Tan-te"},
            {nl:"Neef", en:"Nephew/Cousin (m)", ph:"Nayf"}, {nl:"Nicht", en:"Niece/Cousin (f)", ph:"Nikht"},
            // Animals
            {nl:"Hond", en:"Dog", ph:"Hont"}, {nl:"Kat", en:"Cat", ph:"Kat"},
            {nl:"Vogel", en:"Bird", ph:"Foh-ghel"}, {nl:"Vis", en:"Fish", ph:"Fis"},
            {nl:"Paard", en:"Horse", ph:"Part"}, {nl:"Koe", en:"Cow", ph:"Koo"},
            {nl:"Varken", en:"Pig", ph:"Far-ken"}, {nl:"Kip", en:"Chicken", ph:"Kip"},
            {nl:"Konijn", en:"Rabbit", ph:"Ko-nayn"}, {nl:"Muis", en:"Mouse", ph:"Mows"},
            {nl:"Leeuw", en:"Lion", ph:"Lay-uw"}, {nl:"Tijger", en:"Tiger", ph:"Tay-gher"},
            {nl:"Beer", en:"Bear", ph:"Bayr"}, {nl:"Olifant", en:"Elephant", ph:"Oh-lee-fant"},
            // Food & Drink
            {nl:"Water", en:"Water", ph:"Fah-ter"}, {nl:"Brood", en:"Bread", ph:"Broht"},
            {nl:"Melk", en:"Milk", ph:"Melk"}, {nl:"Kaas", en:"Cheese", ph:"Kahs"},
            {nl:"Vlees", en:"Meat", ph:"Vlays"}, {nl:"Ei", en:"Egg", ph:"Ay"},
            {nl:"Rijst", en:"Rice", ph:"Rayst"}, {nl:"Soep", en:"Soup", ph:"Soop"},
            {nl:"Zout", en:"Salt", ph:"Zowt"}, {nl:"Suiker", en:"Sugar", ph:"Sow-ker"},
            {nl:"Koffie", en:"Coffee", ph:"Ko-fee"}, {nl:"Thee", en:"Tea", ph:"Tay"},
            {nl:"Bier", en:"Beer", ph:"Beer"}, {nl:"Wijn", en:"Wine", ph:"Vayn"},
            {nl:"Sap", en:"Juice", ph:"Sap"}, {nl:"Groente", en:"Vegetables", ph:"Ghroon-te"},
            {nl:"Fruit", en:"Fruit", ph:"Frowt"},
            // Nature & Weather
            {nl:"Zon", en:"Sun", ph:"Zon"}, {nl:"Maan", en:"Moon", ph:"Mahn"},
            {nl:"Ster", en:"Star", ph:"Stayr"}, {nl:"Regen", en:"Rain", ph:"Ray-ghen"},
            {nl:"Sneeuw", en:"Snow", ph:"Snayw"}, {nl:"Wind", en:"Wind", ph:"Wint"},
            {nl:"Vuur", en:"Fire", ph:"Fyoor"}, {nl:"Aarde", en:"Earth/Soil", ph:"Ar-de"},
            {nl:"Zee", en:"Sea", ph:"Zay"}, {nl:"Rivier", en:"River", ph:"Ree-veer"},
            {nl:"Berg", en:"Mountain", ph:"Berkh"}, {nl:"Bos", en:"Forest", ph:"Bos"},
            {nl:"Boom", en:"Tree", ph:"Bohm"}, {nl:"Bloem", en:"Flower", ph:"Bloom"},
            {nl:"Steen", en:"Stone/Rock", ph:"Stayn"}, {nl:"Zand", en:"Sand", ph:"Zant"},
            {nl:"Wolk", en:"Cloud", ph:"Wolk"}, {nl:"Hemel", en:"Sky/Heaven", ph:"Hay-mel"},
            // Common adjectives
            {nl:"Groot", en:"Big", ph:"Ghrohf"}, {nl:"Klein", en:"Small", ph:"Klayn"},
            {nl:"Nieuw", en:"New", ph:"Nyow"}, {nl:"Oud", en:"Old", ph:"Owt"},
            {nl:"Goed", en:"Good", ph:"Ghoot"}, {nl:"Slecht", en:"Bad", ph:"Slekht"},
            {nl:"Snel", en:"Fast", ph:"Snel"}, {nl:"Langzaam", en:"Slow", ph:"Lang-zahm"},
            {nl:"Warm", en:"Warm/Hot", ph:"Warm"}, {nl:"Koud", en:"Cold", ph:"Kowt"},
            {nl:"Blij", en:"Happy", ph:"Blay"}, {nl:"Verdrietig", en:"Sad", ph:"Ver-dree-tikh"},
            {nl:"Mooi", en:"Beautiful", ph:"Moy"}, {nl:"Lelijk", en:"Ugly", ph:"Lay-lik"},
            // Common verbs
            {nl:"Eten", en:"To eat", ph:"Ay-ten"}, {nl:"Drinken", en:"To drink", ph:"Drink-en"},
            {nl:"Slapen", en:"To sleep", ph:"Slah-pen"}, {nl:"Lopen", en:"To walk", ph:"Loh-pen"},
            {nl:"Rennen", en:"To run", ph:"Ren-nen"}, {nl:"Praten", en:"To talk", ph:"Prah-ten"},
            {nl:"Luisteren", en:"To listen", ph:"Low-ster-en"}, {nl:"Zien", en:"To see", ph:"Zeen"},
            {nl:"Lezen", en:"To read", ph:"Lay-zen"}, {nl:"Schrijven", en:"To write", ph:"Skhray-ven"},
            // Places
            {nl:"Huis", en:"House", ph:"Hows"}, {nl:"School", en:"School", ph:"Skohl"},
            {nl:"Winkel", en:"Shop", ph:"Wink-el"}, {nl:"Bank", en:"Bank", ph:"Bank"},
            {nl:"Ziekenhuis", en:"Hospital", ph:"Zee-ken-hows"}, {nl:"Kerk", en:"Church", ph:"Kayrk"},
            {nl:"Strand", en:"Beach", ph:"Strant"}, {nl:"Park", en:"Park", ph:"Park"},
            {nl:"Luchthaven", en:"Airport", ph:"Lukht-hah-ven"}, {nl:"Station", en:"Station", ph:"Stah-syon"},
        ],
        medium: [
            // Verbs
            {nl:"Vinden", en:"To find", ph:"Fin-den"}, {nl:"Nodig hebben", en:"To need", ph:"Noh-dikh heb-ben"},
            {nl:"Begrijpen", en:"To understand", ph:"Be-ghray-pen"}, {nl:"Kennen", en:"To know (person)", ph:"Ken-nen"},
            {nl:"Weten", en:"To know (fact)", ph:"Way-ten"}, {nl:"Willen", en:"To want", ph:"Wil-len"},
            {nl:"Kunnen", en:"To be able to", ph:"Kun-nen"}, {nl:"Moeten", en:"To have to/must", ph:"Moo-ten"},
            {nl:"Meebrengen", en:"To bring along", ph:"May-breng-en"}, {nl:"Meenemen", en:"To take along", ph:"May-nay-men"},
            {nl:"Vragen", en:"To ask", ph:"Frah-ghen"}, {nl:"Antwoorden", en:"To answer", ph:"Ant-woor-den"},
            {nl:"Helpen", en:"To help", ph:"Hel-pen"}, {nl:"Beginnen", en:"To begin", ph:"Be-ghin-nen"},
            {nl:"Stoppen", en:"To stop", ph:"Stop-pen"}, {nl:"Veranderen", en:"To change", ph:"Ver-an-der-en"},
            {nl:"Verbeteren", en:"To improve", ph:"Ver-bay-ter-en"}, {nl:"Verliezen", en:"To lose", ph:"Ver-lee-zen"},
            {nl:"Winnen", en:"To win", ph:"Win-nen"}, {nl:"Proberen", en:"To try", ph:"Pro-bay-ren"},
            {nl:"Wachten", en:"To wait", ph:"Wakh-ten"}, {nl:"Terugkomen", en:"To return", ph:"Te-ruhg-koh-men"},
            {nl:"Vertrekken", en:"To leave/depart", ph:"Ver-trek-ken"}, {nl:"Binnenkomen", en:"To enter", ph:"Bin-nen-koh-men"},
            {nl:"Openen", en:"To open", ph:"Oh-pen-en"}, {nl:"Sluiten", en:"To close", ph:"Slow-ten"},
            {nl:"Kopen", en:"To buy", ph:"Koh-pen"}, {nl:"Verkopen", en:"To sell", ph:"Ver-koh-pen"},
            {nl:"Betalen", en:"To pay", ph:"Be-tah-len"}, {nl:"Wonen", en:"To live (reside)", ph:"Woh-nen"},
            {nl:"Reizen", en:"To travel", ph:"Ray-zen"}, {nl:"Denken", en:"To think", ph:"Denk-en"},
            {nl:"Geloven", en:"To believe", ph:"Ghe-loh-ven"}, {nl:"Voelen", en:"To feel", ph:"Foo-len"},
            {nl:"Herinneren", en:"To remember", ph:"Her-in-er-en"}, {nl:"Vergeten", en:"To forget", ph:"Ver-ghe-ten"},
            {nl:"Kiezen", en:"To choose", ph:"Kee-zen"}, {nl:"Beslissen", en:"To decide", ph:"Be-slis-sen"},
            {nl:"Uitleggen", en:"To explain", ph:"Owt-leg-ghen"}, {nl:"Leren", en:"To learn/teach", ph:"Lay-ren"},
            // Nouns — Home & Objects
            {nl:"Bank (meubel)", en:"Sofa/Couch", ph:"Bank"}, {nl:"Bed", en:"Bed", ph:"Bet"},
            {nl:"Kussen", en:"Pillow/Cushion", ph:"Kus-sen"}, {nl:"Deken", en:"Blanket", ph:"Day-ken"},
            {nl:"Kast", en:"Wardrobe/Cabinet", ph:"Kast"}, {nl:"Lade", en:"Drawer", ph:"Lah-de"},
            {nl:"Koelkast", en:"Refrigerator", ph:"Kool-kast"}, {nl:"Fornuis", en:"Stove/Cooker", ph:"For-nows"},
            {nl:"Magnetron", en:"Microwave", ph:"Mahg-ne-tron"}, {nl:"Douche", en:"Shower", ph:"Doo-she"},
            {nl:"Badkamer", en:"Bathroom", ph:"Bat-kah-mer"}, {nl:"Tuin", en:"Garden", ph:"Town"},
            {nl:"Balkon", en:"Balcony", ph:"Bal-kon"}, {nl:"Trap", en:"Stairs", ph:"Trap"},
            {nl:"Plafond", en:"Ceiling", ph:"Plah-fon"}, {nl:"Muur", en:"Wall", ph:"Myoor"},
            {nl:"Vloer", en:"Floor", ph:"Vloor"}, {nl:"Raam", en:"Window", ph:"Rahm"},
            {nl:"Deur", en:"Door", ph:"Dur"}, {nl:"Tafel", en:"Table", ph:"Tah-fel"},
            {nl:"Stoel", en:"Chair", ph:"Stool"}, {nl:"Lamp", en:"Lamp", ph:"Lamp"},
            // Transport & City
            {nl:"Bus", en:"Bus", ph:"Bus"}, {nl:"Metro", en:"Subway/Metro", ph:"May-troh"},
            {nl:"Trein", en:"Train", ph:"Trayn"}, {nl:"Vliegtuig", en:"Airplane", ph:"Fleekh-towkh"},
            {nl:"Taxi", en:"Taxi", ph:"Tax-ee"}, {nl:"Fiets", en:"Bicycle", ph:"Feets"},
            {nl:"Motor", en:"Motorcycle", ph:"Moh-tor"}, {nl:"Wijk", en:"Neighbourhood", ph:"Wayk"},
            {nl:"Plein", en:"Square/Plaza", ph:"Playn"}, {nl:"Hoek", en:"Corner", ph:"Hook"},
            {nl:"Stoplicht", en:"Traffic light", ph:"Stop-likht"}, {nl:"Stoep", en:"Pavement/Sidewalk", ph:"Stoop"},
            {nl:"Brug", en:"Bridge", ph:"Bruhg"}, {nl:"Straat", en:"Street", ph:"Straht"},
            {nl:"Weg", en:"Road/Way", ph:"Wekh"},
            // Adjectives
            {nl:"Moe", en:"Tired", ph:"Moo"}, {nl:"Druk", en:"Busy", ph:"Druhk"},
            {nl:"Vrij", en:"Free", ph:"Vray"}, {nl:"Vol", en:"Full", ph:"Fol"},
            {nl:"Leeg", en:"Empty", ph:"Laykh"}, {nl:"Zwaar", en:"Heavy", ph:"Zwar"},
            {nl:"Licht", en:"Light (weight)", ph:"Likht"}, {nl:"Breed", en:"Wide", ph:"Brayt"},
            {nl:"Smal", en:"Narrow", ph:"Smal"}, {nl:"Hoog", en:"High/Tall", ph:"Hohkh"},
            {nl:"Laag", en:"Low/Short", ph:"Lahkh"}, {nl:"Dik", en:"Fat/Thick", ph:"Dik"},
            {nl:"Dun", en:"Thin", ph:"Duhn"}, {nl:"Sterk", en:"Strong", ph:"Stayrk"},
            {nl:"Zwak", en:"Weak", ph:"Zwak"}, {nl:"Reich", en:"Rich", ph:"Rayk"},
            {nl:"Arm", en:"Poor", ph:"Arm"}, {nl:"Alleen", en:"Alone", ph:"A-layn"},
            {nl:"Samen", en:"Together", ph:"Sah-men"}, {nl:"Anders", en:"Different", ph:"An-ders"},
            {nl:"Hetzelfde", en:"The same", ph:"Het-zel-fde"}, {nl:"Veilig", en:"Safe", ph:"Fay-likh"},
            {nl:"Gevaarlijk", en:"Dangerous", ph:"Ghe-far-lik"}, {nl:"Beroemd", en:"Famous", ph:"Be-roomt"},
            {nl:"Vreemd", en:"Strange", ph:"Vraymт"}, {nl:"Gestrest", en:"Stressed", ph:"Ghe-strest"},
            // Food & Meals
            {nl:"Ontbijt", en:"Breakfast", ph:"Ont-bayt"}, {nl:"Lunch", en:"Lunch", ph:"Lunsh"},
            {nl:"Avondeten", en:"Dinner", ph:"Ah-vont-ay-ten"}, {nl:"Nagerecht", en:"Dessert", ph:"Nah-ghe-rekht"},
            {nl:"Salade", en:"Salad", ph:"Sa-lah-de"}, {nl:"Pasta", en:"Pasta", ph:"Pas-ta"},
            {nl:"Taart", en:"Cake/Tart", ph:"Tart"}, {nl:"Koekje", en:"Cookie/Biscuit", ph:"Kook-ye"},
            {nl:"Ijs", en:"Ice cream", ph:"Ays"}, {nl:"Boter", en:"Butter", ph:"Boh-ter"},
            {nl:"Olie", en:"Oil", ph:"Oh-lee"}, {nl:"Azijn", en:"Vinegar", ph:"A-zayn"},
            {nl:"Peper", en:"Pepper", ph:"Pay-per"}, {nl:"Knoflook", en:"Garlic", ph:"Knof-lohk"},
            {nl:"Ui", en:"Onion", ph:"Ow"}, {nl:"Tomaat", en:"Tomato", ph:"To-maht"},
            {nl:"Aardappel", en:"Potato", ph:"Art-ap-el"}, {nl:"Wortel", en:"Carrot", ph:"Vor-tel"},
            {nl:"Sla", en:"Lettuce", ph:"Slah"}, {nl:"Appel", en:"Apple", ph:"Ap-el"},
            // Time & Calendar
            {nl:"Gisteren", en:"Yesterday", ph:"Ghis-ter-en"}, {nl:"Vandaag", en:"Today", ph:"Fan-dahkh"},
            {nl:"Morgen", en:"Tomorrow", ph:"Mor-ghen"}, {nl:"Week", en:"Week", ph:"Wayk"},
            {nl:"Maand", en:"Month", ph:"Mahnt"}, {nl:"Jaar", en:"Year", ph:"Yar"},
            {nl:"Uur", en:"Hour", ph:"Yoor"}, {nl:"Minuut", en:"Minute", ph:"Mee-nyoot"},
            {nl:"Seconde", en:"Second", ph:"Se-kon-de"}, {nl:"Maandag", en:"Monday", ph:"Mahn-dakh"},
            {nl:"Dinsdag", en:"Tuesday", ph:"Dins-dakh"}, {nl:"Woensdag", en:"Wednesday", ph:"Woons-dakh"},
            {nl:"Donderdag", en:"Thursday", ph:"Don-der-dakh"}, {nl:"Vrijdag", en:"Friday", ph:"Fray-dakh"},
            {nl:"Zaterdag", en:"Saturday", ph:"Zah-ter-dakh"}, {nl:"Zondag", en:"Sunday", ph:"Zon-dakh"},
            // Emotions
            {nl:"Angst", en:"Fear/Anxiety", ph:"Angst"}, {nl:"Woede", en:"Anger", ph:"Woo-de"},
            {nl:"Vreugde", en:"Joy", ph:"Vrurk-de"}, {nl:"Verdriet", en:"Sadness/Grief", ph:"Ver-dreet"},
            {nl:"Verrassing", en:"Surprise", ph:"Ver-ras-sing"}, {nl:"Schaamte", en:"Shame", ph:"Skham-te"},
            {nl:"Trots", en:"Pride", ph:"Trots"}, {nl:"Jaloezie", en:"Jealousy", ph:"Ya-loo-zee"},
            {nl:"Afgunst", en:"Envy", ph:"Af-ghunst"}, {nl:"Kalmte", en:"Calm", ph:"Kalm-te"},
            // Health
            {nl:"Dokter", en:"Doctor", ph:"Dok-ter"}, {nl:"Medicijn", en:"Medicine", ph:"May-dee-sayn"},
            {nl:"Pijn", en:"Pain", ph:"Payn"}, {nl:"Koorts", en:"Fever", ph:"Kohrts"},
            {nl:"Hoest", en:"Cough", ph:"Hoost"}, {nl:"Verkoudheid", en:"Cold (illness)", ph:"Ver-kowt-hayt"},
            {nl:"Vermoeidheid", en:"Fatigue", ph:"Ver-mooy-hayt"}, {nl:"Gezondheid", en:"Health", ph:"Ghe-zont-hayt"},
        ],
        hard: [
            // Abstract nouns
            {nl:"Bewustzijn", en:"Consciousness/Awareness", ph:"Be-wust-zayn"}, {nl:"Gedrag", en:"Behaviour", ph:"Ghe-drakh"},
            {nl:"Verantwoordelijkheid", en:"Responsibility", ph:"Ver-ant-woor-de-lik-hayt"}, {nl:"Gevolg", en:"Consequence/Result", ph:"Ghe-folk"},
            {nl:"Ervaring", en:"Experience", ph:"Er-fah-ring"}, {nl:"Invloed", en:"Influence", ph:"In-floot"},
            {nl:"Onafhankelijkheid", en:"Independence", ph:"On-af-hank-e-lik-hayt"}, {nl:"Transparantie", en:"Transparency", ph:"Trans-pa-ran-see"},
            {nl:"Volharding", en:"Persistence", ph:"Fol-har-ding"}, {nl:"Bekwaamheid", en:"Competence", ph:"Be-kwahm-hayt"},
            {nl:"Nieuwsgierigheid", en:"Curiosity", ph:"Nyows-ghee-rikh-hayt"}, {nl:"Mogelijkheid", en:"Possibility", ph:"Moh-ghe-lik-hayt"},
            {nl:"Noodzakelijkheid", en:"Necessity", ph:"Noht-zah-ke-lik-hayt"}, {nl:"Werkelijkheid", en:"Reality", ph:"Wer-ke-lik-hayt"},
            {nl:"Persoonlijkheid", en:"Personality", ph:"Per-sohn-lik-hayt"}, {nl:"Identiteit", en:"Identity", ph:"Ee-den-tee-tayt"},
            {nl:"Complexiteit", en:"Complexity", ph:"Com-plek-see-tayt"}, {nl:"Menselijkheid", en:"Humanity", ph:"Men-se-lik-hayt"},
            {nl:"Grootmoedigheid", en:"Generosity", ph:"Grohl-moo-dikh-hayt"}, {nl:"Creativiteit", en:"Creativity", ph:"Kray-ah-tee-fee-tayt"},
            {nl:"Solidariteit", en:"Solidarity", ph:"So-lee-da-ree-tayt"}, {nl:"Duurzaamheid", en:"Sustainability", ph:"Dyoor-zahm-hayt"},
            {nl:"Erkenning", en:"Recognition", ph:"Er-ken-ning"}, {nl:"Zelfkennis", en:"Self-knowledge", ph:"Zelf-ken-is"},
            {nl:"Ontwikkeling", en:"Development", ph:"Ont-wik-ke-ling"}, {nl:"Samenleving", en:"Society", ph:"Sah-men-lay-ving"},
            {nl:"Cultuur", en:"Culture", ph:"Kul-tyoor"}, {nl:"Wetenschap", en:"Science", ph:"Way-ten-skhap"},
            {nl:"Technologie", en:"Technology", ph:"Tek-no-loh-zhee"}, {nl:"Filosofie", en:"Philosophy", ph:"Fee-lo-soh-fee"},
            {nl:"Onderwijs", en:"Education", ph:"On-der-ways"}, {nl:"Onderzoek", en:"Research", ph:"On-der-zook"},
            {nl:"Rechtvaardigheid", en:"Justice/Fairness", ph:"Rekht-far-dikh-hayt"}, {nl:"Vrijheid", en:"Freedom", ph:"Fray-hayt"},
            {nl:"Gelijkheid", en:"Equality", ph:"Ghe-layk-hayt"}, {nl:"Veiligheid", en:"Safety/Security", ph:"Fay-likh-hayt"},
            // Complex verbs
            {nl:"Begrijpen", en:"To understand (fully)", ph:"Be-ghray-pen"}, {nl:"Ontwikkelen", en:"To develop", ph:"Ont-wik-ke-len"},
            {nl:"Vaststellen", en:"To establish/determine", ph:"Fast-stel-len"}, {nl:"Uitvoeren", en:"To implement/carry out", ph:"Owt-foo-ren"},
            {nl:"Beheren", en:"To manage/administer", ph:"Be-hay-ren"}, {nl:"Communiceren", en:"To communicate", ph:"Ko-myoo-nee-say-ren"},
            {nl:"Aantonen", en:"To demonstrate", ph:"Ahn-toh-nen"}, {nl:"Vertegenwoordigen", en:"To represent", ph:"Ver-tay-ghen-woor-di-ghen"},
            {nl:"Interpreteren", en:"To interpret", ph:"In-ter-pre-tay-ren"}, {nl:"Transformeren", en:"To transform", ph:"Trans-for-may-ren"},
            {nl:"Overwinnen", en:"To overcome", ph:"Oh-ver-win-nen"}, {nl:"Verlaten", en:"To abandon", ph:"Ver-lah-ten"},
            {nl:"Bijdragen", en:"To contribute", ph:"Bay-drah-ghen"}, {nl:"Overwegen", en:"To consider", ph:"Oh-ver-way-ghen"},
            {nl:"Aanbevelen", en:"To recommend", ph:"Ahn-be-vay-len"}, {nl:"Verrassen", en:"To surprise", ph:"Ver-ras-sen"},
            {nl:"Beïnvloeden", en:"To influence", ph:"Be-in-floo-den"}, {nl:"Analyseren", en:"To analyse", ph:"A-na-lee-zay-ren"},
            {nl:"Organiseren", en:"To organise", ph:"Or-gha-nee-zay-ren"}, {nl:"Realiseren", en:"To realise/achieve", ph:"Ray-a-lee-zay-ren"},
            // Hard adjectives
            {nl:"Indrukwekkend", en:"Impressive", ph:"In-druhk-wek-ent"}, {nl:"Uitdagend", en:"Challenging", ph:"Owt-dah-ghent"},
            {nl:"Ongelooflijk", en:"Unbelievable", ph:"On-ghe-lohf-lik"}, {nl:"Onmisbaar", en:"Indispensable", ph:"On-mis-bar"},
            {nl:"Onverantwoordelijk", en:"Irresponsible", ph:"On-ver-ant-woor-de-lik"}, {nl:"Onbegrijpelijk", en:"Incomprehensible", ph:"On-be-ghray-pe-lik"},
            {nl:"Eindeloos", en:"Endless", ph:"Ayn-de-lohs"}, {nl:"Nauwkeurig", en:"Accurate/Precise", ph:"Naw-kur-ikh"},
            {nl:"Passend", en:"Appropriate", ph:"Pas-sent"}, {nl:"Concreet", en:"Concrete/Specific", ph:"Con-krayt"},
            {nl:"Abstract", en:"Abstract", ph:"Ab-strakt"}, {nl:"Proactief", en:"Proactive", ph:"Pro-ak-teef"},
            {nl:"Logisch", en:"Logical", ph:"Loh-ghis"}, {nl:"Realistisch", en:"Realistic", ph:"Ray-a-lees-tis"},
            {nl:"Emotioneel", en:"Emotional", ph:"Ay-moh-syo-nayl"},
            // Society, history, politics
            {nl:"Geschiedenis", en:"History", ph:"Ghe-skhee-de-nis"}, {nl:"Politiek", en:"Politics", ph:"Po-lee-teek"},
            {nl:"Economie", en:"Economy", ph:"Ay-ko-no-mee"}, {nl:"Omgeving", en:"Environment", ph:"Om-ghay-ving"},
            {nl:"Recht", en:"Law/Right", ph:"Rekht"}, {nl:"Muziek", en:"Music", ph:"Myoo-zeek"},
            {nl:"Architectuur", en:"Architecture", ph:"Ar-khee-tek-tyoor"}, {nl:"Landbouw", en:"Agriculture", ph:"Lant-baw"},
            {nl:"Industrie", en:"Industry", ph:"In-dus-tree"}, {nl:"Handel", en:"Trade/Commerce", ph:"Han-del"},
            {nl:"Resultaat", en:"Result/Outcome", ph:"Re-zul-taht"}, {nl:"Oorzaak", en:"Cause/Reason", ph:"Ohr-zahk"},
            {nl:"Doel", en:"Goal/Purpose", ph:"Dool"}, {nl:"Methode", en:"Method", ph:"May-toh-de"},
            {nl:"Situatie", en:"Situation", ph:"See-too-ah-see"}, {nl:"Reden", en:"Reason", ph:"Ray-den"},
            {nl:"Verhouding", en:"Relationship/Ratio", ph:"Ver-how-ding"}, {nl:"Standpunt", en:"Standpoint/Opinion", ph:"Stant-punt"}, {nl:"Begrip", en:"Understanding/Concept", ph:"Be-ghrip"}, {nl:"Waarde", en:"Value/Worth", ph:"War-de"},
        ],
        vhard: [
            {nl:"Verantwoordelijkheidszin", en:"Sense of responsibility", ph:"Ver-ant-woor-de-lik-hayts-zin"},
            {nl:"Meningsuiting", en:"Freedom of expression", ph:"May-nings-ow-ting"},
            {nl:"Gezondheidszorg", en:"Healthcare", ph:"Ghe-zont-hayts-zorkh"},
            {nl:"Werkloosheidsuitkering", en:"Unemployment benefit", ph:"Werk-lohs-hayts-owt-kay-ring"},
            {nl:"Rijksbelastingdienst", en:"National Tax Authority", ph:"Rayks-be-las-ting-deenst"},
            {nl:"Aansprakelijkheidsver­zekering", en:"Liability insurance", ph:"Ahn-sprah-ke-lik-hayts-ver-zay-ke-ring"},
            {nl:"Kinderopvangtoeslag", en:"Childcare allowance", ph:"Kin-der-op-fang-too-slakh"},
            {nl:"Vliegtuigmaatschappij", en:"Airline company", ph:"Fleekh-towkh-maht-skhap-ay"},
            {nl:"Rechtsvaardigheidsgevoel", en:"Sense of justice", ph:"Rekhts-far-dikh-hayts-ghe-fool"},
            {nl:"Persoonlijkheidsontwikkeling", en:"Personal development", ph:"Per-sohn-lik-hayts-ont-wik-ke-ling"},
            {nl:"Ziekenhuisopname", en:"Hospital admission", ph:"Zee-ken-hows-op-nah-me"},
            {nl:"Volksvertegenwoordiging", en:"People's representation/Parliament", ph:"Folks-ver-tay-ghen-woor-di-ghng"},
            {nl:"Maatschappelijkebetrokkenheid", en:"Social engagement", ph:"Maht-skhap-e-like-be-trok-en-hayt"},
            {nl:"Bewustzijnsverruiming", en:"Expansion of consciousness", ph:"Be-wust-zayns-ver-row-ming"},
            {nl:"Grondwettelijkheid", en:"Constitutionality", ph:"Ghront-wet-e-lik-hayt"},
            {nl:"Doorgroeimogelijkheden", en:"Career advancement opportunities", ph:"Dohr-ghroo-ee-moh-ghe-lik-hay-den"},
            {nl:"Beroepsaansprakelijkheid", en:"Professional liability", ph:"Be-roo-ps-ahn-sprah-ke-lik-hayt"},
            {nl:"Staatsrechtelijke", en:"Constitutional/Public law (adj.)", ph:"Stahts-rekht-e-like"},
            {nl:"Verkeersaansprakelijkheid", en:"Traffic liability", ph:"Ver-kayrs-ahn-sprah-ke-lik-hayt"},
            {nl:"Klimaatverandering", en:"Climate change", ph:"Klee-maht-ver-an-der-ing"},
        ]
    },
    phrases: {
        easy: [
            {nl:"Hallo!", en:"Hello!", ph:"Ha-lo"}, {nl:"Hoi!", en:"Hi!", ph:"Hoy"},
            {nl:"Goedemorgen!", en:"Good morning!", ph:"Ghoo-de-mor-ghen"}, {nl:"Goedemiddag!", en:"Good afternoon!", ph:"Ghoo-de-mid-dakh"},
            {nl:"Goedenavond!", en:"Good evening!", ph:"Ghoo-den-ah-font"}, {nl:"Goedenacht!", en:"Good night!", ph:"Ghoo-den-akht"},
            {nl:"Dag!/Doei!", en:"Bye!", ph:"Dakh/Doo-ee"}, {nl:"Tot ziens!", en:"See you!", ph:"Tot zeens"},
            {nl:"Tot morgen!", en:"See you tomorrow!", ph:"Tot mor-ghen"}, {nl:"Alsjeblieft", en:"Please (informal)", ph:"Als-ye-bleeft"},
            {nl:"Alstublieft", en:"Please (formal)", ph:"Als-too-bleeft"}, {nl:"Dank je wel", en:"Thank you (informal)", ph:"Dank ye wel"},
            {nl:"Dank u wel", en:"Thank you (formal)", ph:"Dank oo wel"}, {nl:"Graag gedaan", en:"You're welcome", ph:"Ghrahkh ghe-dahn"},
            {nl:"Excuseer me", en:"Excuse me", ph:"Ex-kyoo-zayr me"}, {nl:"Sorry", en:"Sorry", ph:"So-ree"},
            {nl:"Hoe gaat het?", en:"How are you?", ph:"Hoo ghaht het"}, {nl:"Goed, dank je!", en:"Fine, thank you!", ph:"Ghoot dank ye"},
            {nl:"Ja", en:"Yes", ph:"Yah"}, {nl:"Nee", en:"No", ph:"Nay"},
            {nl:"Misschien", en:"Maybe", ph:"Mis-kheen"}, {nl:"Ik weet het niet", en:"I don't know", ph:"Ik wayt het neet"},
            {nl:"Ik begrijp het", en:"I understand", ph:"Ik be-ghrayp het"}, {nl:"Ik begrijp het niet", en:"I don't understand", ph:"Ik be-ghrayp het neet"},
            {nl:"Kunt u dat herhalen?", en:"Can you repeat that?", ph:"Kunt oo dat her-hah-len"}, {nl:"Spreek langzamer, alsjeblieft", en:"Speak more slowly please", ph:"Sprayk lang-zahm-er"},
            {nl:"Waar is het toilet?", en:"Where is the toilet?", ph:"War is het twah-let"}, {nl:"Hoeveel kost het?", en:"How much does it cost?", ph:"Hoo-fayl kost het"},
            {nl:"Hoe heet u?", en:"What is your name? (formal)", ph:"Hoo hayt oo"}, {nl:"Ik heet...", en:"My name is...", ph:"Ik hayt"},
            {nl:"Aangenaam!", en:"Nice to meet you!", ph:"Ahn-ghe-nahm"}, {nl:"Gefeliciteerd!", en:"Congratulations!", ph:"Ghe-fe-lee-see-tayrt"},
            {nl:"Fijne verjaardag!", en:"Happy birthday!", ph:"Fay-ne ver-yar-dakh"}, {nl:"Prettig Kerstfeest!", en:"Merry Christmas!", ph:"Pret-ikh kerst-fayst"},
            {nl:"Veel succes!", en:"Good luck!", ph:"Fayl su-ses"}, {nl:"Ik heb honger", en:"I'm hungry", ph:"Ik hep hong-er"},
            {nl:"Ik heb dorst", en:"I'm thirsty", ph:"Ik hep dorst"}, {nl:"Ik ben moe", en:"I'm tired", ph:"Ik ben moo"},
            // More easy phrases
            {nl:"Hoe laat is het?", en:"What time is it?", ph:"Hoo laht is het"}, {nl:"Welke dag is het?", en:"What day is it?", ph:"Wel-ke dakh is het"},
            {nl:"Wat leuk!", en:"How nice!/How fun!", ph:"Wat lurk"}, {nl:"Wat jammer!", en:"What a shame!", ph:"Wat yam-er"},
            {nl:"Wat mooi!", en:"How beautiful!", ph:"Wat moy"}, {nl:"Wat lekker!", en:"How delicious!", ph:"Wat lek-er"},
            {nl:"Kom mee!", en:"Come along!/Let's go!", ph:"Kom may"}, {nl:"Geen probleem!", en:"No problem!", ph:"Ghayn pro-blaym"},
            {nl:"Doe je best!", en:"Do your best!", ph:"Doo ye best"}, {nl:"Eet smakelijk!", en:"Enjoy your meal!", ph:"Ayt smah-ke-lik"},
            {nl:"Goede reis!", en:"Have a good trip!", ph:"Ghoo-de rays"}, {nl:"Pas goed op jezelf!", en:"Take care of yourself!", ph:"Pas ghoot op ye-zelf"},
            {nl:"Waar kom jij vandaan?", en:"Where are you from?", ph:"War kom yay fan-dahn"}, {nl:"Ik kom uit...", en:"I come from...", ph:"Ik kom owt"},
        ],
        medium: [
            {nl:"Ik woon al twee jaar in Nederland", en:"I have been living in the Netherlands for two years", ph:"Ik wohn al tway yar in Nay-der-lant"},
            {nl:"Kunt u mij helpen, alsjeblieft?", en:"Can you help me, please?", ph:"Kunt oo may hel-pen"},
            {nl:"Wat is het beste restaurant hier in de buurt?", en:"What is the best restaurant around here?", ph:"Wat is het bes-te res-toh-rant heer in de byoort"},
            {nl:"Ik leer Nederlands", en:"I am learning Dutch", ph:"Ik layr Nay-der-lants"},
            {nl:"Dat klopt niet helemaal", en:"That's not quite right", ph:"Dat klopt neet hay-le-mahl"},
            {nl:"Dat hangt af van de situatie", en:"That depends on the situation", ph:"Dat hangt af fan de see-too-ah-see"},
            {nl:"Mag ik je later bellen?", en:"May I call you later?", ph:"Makh ik ye lah-ter bel-len"},
            {nl:"Wat vind jij hiervan?", en:"What do you think about this?", ph:"Wat fint yay heer-fan"},
            {nl:"Ik heb een uur nodig om het af te maken", en:"I need an hour to finish it", ph:"Ik hep en yoor noh-dikh om het af te mah-ken"},
            {nl:"Ben je ooit in Amsterdam geweest?", en:"Have you ever been to Amsterdam?", ph:"Ben ye oh-eet in Am-ster-dam ghe-wayst"},
            {nl:"Zullen we volgende week afspreken?", en:"Shall we arrange to meet next week?", ph:"Zul-len we fol-ghende wayk af-spray-ken"},
            {nl:"Ik blijf liever vandaag thuis", en:"I prefer to stay home today", ph:"Ik blay lee-ver fan-dakh tows"},
            {nl:"Spreek je nog een andere taal?", en:"Do you speak any other language?", ph:"Sprayk ye nokh en an-de-re tahl"},
            {nl:"Dit is heel belangrijk voor mij", en:"This is very important to me", ph:"Dit is hayl be-lang-rayk for may"},
            {nl:"Wat voor muziek luister jij?", en:"What kind of music do you listen to?", ph:"Wat for myoo-zeek low-ster yay"},
            {nl:"Ik heb hoofdpijn", en:"I have a headache", ph:"Ik hep hohft-payn"},
            {nl:"Hoe lang duurt het om er te komen?", en:"How long does it take to get there?", ph:"Hoo lang dyoort het om er te koh-men"},
            {nl:"Kun jij me een hint geven?", en:"Can you give me a hint?", ph:"Kun yay me en hint ghay-ven"},
            {nl:"Ik dacht net aan jou", en:"I was just thinking about you", ph:"Ik dakht net ahn yow"},
            {nl:"Dat maakt me heel blij", en:"That makes me very happy", ph:"Dat mahkt me hayl blay"},
            {nl:"Wil je iets drinken?", en:"Would you like something to drink?", ph:"Wil ye eets drink-en"},
            {nl:"Ik kan niet slapen", en:"I can't sleep", ph:"Ik kan neet slah-pen"},
            {nl:"De rekening, alsjeblieft", en:"The bill, please", ph:"De ray-ke-ning als-ye-bleeft"},
            {nl:"Is er een probleem?", en:"Is there a problem?", ph:"Is er en pro-blaym"},
            {nl:"Ik zal erover nadenken", en:"I will think about it", ph:"Ik zal er-oh-ver nah-denk-en"},
            {nl:"Met wie woon jij?", en:"Who do you live with?", ph:"Met wee wohn yay"},
            {nl:"Welke dag is het vandaag?", en:"What day is today?", ph:"Wel-ke dakh is het fan-dakh"},
            {nl:"De bus komt om negen uur", en:"The bus comes at nine", ph:"De bus komt om nay-ghen yoor"},
            {nl:"Heb je al gegeten vandaag?", en:"Have you eaten today?", ph:"Hep ye al ghe-ghay-ten fan-dakh"},
            {nl:"Ik herinner me dat niet", en:"I don't remember that", ph:"Ik her-in-er me dat neet"},
            // More medium phrases
            {nl:"Waar werk jij?", en:"Where do you work?", ph:"War werk yay"},
            {nl:"Hoe lang leer je al Nederlands?", en:"How long have you been learning Dutch?", ph:"Hoo lang layr ye al Nay-der-lants"},
            {nl:"Ik hou heel veel van Nederlandse muziek", en:"I really love Dutch music", ph:"Ik how hayl fayl fan Nay-der-lan-se myoo-zeek"},
            {nl:"Kun je het op de kaart aanwijzen?", en:"Can you point it out on the map?", ph:"Kun ye het op de kart ahn-way-zen"},
            {nl:"Is er iets vegetarisch op het menu?", en:"Is there anything vegetarian on the menu?", ph:"Is er eets ve-ghe-tah-rees op het me-nyoo"},
            {nl:"Ik moet geld wisselen", en:"I need to exchange money", ph:"Ik moot ghelt wis-se-len"},
            {nl:"Kun je me korting geven?", en:"Can you give me a discount?", ph:"Kun ye me kor-ting ghay-ven"},
            {nl:"Wat vreemd!", en:"How strange!", ph:"Wat vraym"},
            {nl:"Ik ben het niet helemaal met je eens", en:"I don't entirely agree with you", ph:"Ik ben het neet hay-le-mahl met ye ayns"},
        ],
        hard: [
            {nl:"Ik hoop dat alles zich op de best mogelijke manier oplost", en:"I hope everything works out in the best way possible", ph:"Ik hohp dat al-les zikh op de best moh-ghe-like mah-neer op-lost"},
            {nl:"Zou je me kunnen uitleggen hoe het werkt?", en:"Could you explain to me how it works?", ph:"Zow ye me kun-nen owt-leg-ghen hoo het werkt"},
            {nl:"Het is het niet waard om je er nu druk over te maken", en:"It's not worth worrying about that now", ph:"Het is het neet wart om ye er noo druhk oh-ver te mah-ken"},
            {nl:"Ik heb veel te leren van deze ervaring", en:"I have a lot to learn from this experience", ph:"Ik hep fayl te lay-ren fan day-ze er-fah-ring"},
            {nl:"Hoe meer ik oefen, hoe meer ik leer", en:"The more I practise, the more I learn", ph:"Hoo mayr ik oo-fen hoo mayr ik layr"},
            {nl:"Hoe hard ik ook probeer, ik kan niet ophouden met denken", en:"No matter how hard I try, I can't stop thinking", ph:"Hoo hart ik ohk pro-bayr ik kan neet op-how-den met denk-en"},
            {nl:"Het leven is veel meer dan wat we zien", en:"Life is much more than what we see", ph:"Het lay-ven is fayl mayr dan wat we zeen"},
            {nl:"Iedereen heeft een ander perspectief", en:"Everyone has a different perspective", ph:"Ee-der-ayn hayft en an-der pers-pek-teef"},
            {nl:"Het heeft even geduurd, maar we hebben uiteindelijk een akkoord bereikt", en:"It took a while, but we finally reached an agreement", ph:"Het hayft ay-ven ghe-dyoort mar we heb-ben owt-ayn-de-lik en a-kohrt be-raykt"},
            {nl:"Kun jij je voorstellen hoe het zou zijn zonder technologie?", en:"Can you imagine what it would be like without technology?", ph:"Kun yay ye for-stel-len hoo het zow zayn zon-der tek-no-loh-zhee"},
            {nl:"Je hebt geduld nodig om een taal te leren", en:"You need patience to learn a language", ph:"Ye hept ghe-duld noh-dikh om en tahl te lay-ren"},
            {nl:"Zonder communicatie is er geen relatie", en:"Without communication there is no relationship", ph:"Zon-der ko-myoo-nee-kah-see is er ghayn re-lah-see"},
            // More hard phrases
            {nl:"Ik kan niet geloven hoe snel de tijd voorbij gaat", en:"I can't believe how fast time flies", ph:"Ik kan neet ghe-loh-ven hoo snel de tayt for-bay ghaht"},
            {nl:"Ik zou graag meer willen weten over de Nederlandse cultuur", en:"I would like to know more about Dutch culture", ph:"Ik zow ghrahkh mayr wil-len way-ten oh-ver de Nay-der-lan-se kul-tyoor"},
            {nl:"Dat is niet precies wat ik bedoelde", en:"That's not exactly what I meant", ph:"Dat is neet pre-sees wat ik be-dool-de"},
            {nl:"Makkelijker gezegd dan gedaan", en:"Easier said than done", ph:"Mak-ke-li-ker ghe-zekht dan ghe-dahn"},
            {nl:"Soms zegt stilte meer dan woorden", en:"Sometimes silence says more than words", ph:"Soms zekht stil-te mayr dan wor-den"},
        ],
        vhard: [
            // Proverbs & Idioms
            {nl:"Al draagt een aap een gouden ring, het is en blijft een lelijk ding", en:"You can't change what something is on the inside (lit: even a monkey with a gold ring is still ugly)", ph:"Proverb"},
            {nl:"De aanhouder wint", en:"Perseverance pays off", ph:"De ahn-how-der wint"},
            {nl:"Beter één vogel in de hand dan tien in de lucht", en:"A bird in the hand is worth two in the bush", ph:"Proverb"},
            {nl:"Wie niet waagt, wie niet wint", en:"Nothing ventured, nothing gained", ph:"Wee neet wahkht wee neet wint"},
            {nl:"In het land der blinden is éénoog koning", en:"In the land of the blind the one-eyed man is king", ph:"Proverb"},
            {nl:"Oost west, thuis best", en:"There's no place like home", ph:"Ohst west tows best"},
            {nl:"Zoals de waard is, vertrouwt hij zijn gasten", en:"We judge others by our own standards", ph:"Proverb"},
            {nl:"De pot verwijt de ketel dat hij zwart ziet", en:"The pot calling the kettle black", ph:"Proverb"},
            {nl:"Kom niet aan mijn fiets", en:"Don't mess with what's mine (lit: don't touch my bike)", ph:"Idiom"},
            {nl:"Met de deur in huis vallen", en:"To get straight to the point", ph:"Idiom"},
            {nl:"Nu komt de aap uit de mouw", en:"Now the truth comes out (lit: now the monkey comes out of the sleeve)", ph:"Idiom"},
            {nl:"Iemand een koekje van eigen deeg geven", en:"To give someone a taste of their own medicine", ph:"Idiom"},
            {nl:"Van een mug een olifant maken", en:"To make a mountain out of a molehill", ph:"Idiom"},
            {nl:"Niet over één nacht ijs gaan", en:"Not to rush into things", ph:"Idiom"},
            {nl:"Het hemd is nader dan de rok", en:"Charity begins at home", ph:"Proverb"},
            {nl:"Boontje komt om zijn loontje", en:"What goes around comes around", ph:"Proverb"},
            {nl:"Wie goed doet, goed ontmoet", en:"Do good and good will come to you", ph:"Proverb"},
            {nl:"Leugens hebben korte benen", en:"Lies have short legs (lies don't get you far)", ph:"Proverb"},
        ]
    }
};