const JAPANESE_LIBRARY = {
    words: {
        easy: [
            // Original entries
            {jp:"水", en:"Water", rj:"Mizu"}, {jp:"火", en:"Fire", rj:"Hi"}, {jp:"木", en:"Tree", rj:"Ki"},
            {jp:"金", en:"Gold/Money", rj:"Kane"}, {jp:"土", en:"Earth/Soil", rj:"Tsuchi"}, {jp:"日", en:"Sun/Day", rj:"Hi"},
            {jp:"月", en:"Moon/Month", rj:"Tsuki"}, {jp:"円", en:"Yen", rj:"En"}, {jp:"口", en:"Mouth", rj:"Kuchi"},
            {jp:"目", en:"Eye", rj:"Me"}, {jp:"耳", en:"Ear", rj:"Mimi"}, {jp:"手", en:"Hand", rj:"Te"},
            {jp:"足", en:"Leg/Foot", rj:"Ashi"}, {jp:"犬", en:"Dog", rj:"Inu"}, {jp:"猫", en:"Cat", rj:"Neko"},
            {jp:"鳥", en:"Bird", rj:"Tori"}, {jp:"魚", en:"Fish", rj:"Sakana"}, {jp:"花", en:"Flower", rj:"Hana"},
            {jp:"茶", en:"Tea", rj:"Cha"}, {jp:"肉", en:"Meat", rj:"Niku"}, {jp:"卵", en:"Egg", rj:"Tamago"},
            {jp:"米", en:"Rice (uncooked)", rj:"Kome"}, {jp:"雨", en:"Rain", rj:"Ame"}, {jp:"雪", en:"Snow", rj:"Yuki"},
            {jp:"風", en:"Wind", rj:"Kaze"}, {jp:"山", en:"Mountain", rj:"Yama"}, {jp:"川", en:"River", rj:"Kawa"},
            // NEW easy words — Body parts
            {jp:"頭", en:"Head", rj:"Atama"}, {jp:"鼻", en:"Nose", rj:"Hana"}, {jp:"歯", en:"Tooth", rj:"Ha"},
            {jp:"舌", en:"Tongue", rj:"Shita"}, {jp:"首", en:"Neck", rj:"Kubi"}, {jp:"肩", en:"Shoulder", rj:"Kata"},
            {jp:"腕", en:"Arm", rj:"Ude"}, {jp:"指", en:"Finger", rj:"Yubi"}, {jp:"胸", en:"Chest", rj:"Mune"},
            {jp:"背中", en:"Back", rj:"Senaka"}, {jp:"腹", en:"Belly/Stomach", rj:"Hara"}, {jp:"膝", en:"Knee", rj:"Hiza"},
            {jp:"髪", en:"Hair", rj:"Kami"}, {jp:"顔", en:"Face", rj:"Kao"}, {jp:"皮膚", en:"Skin", rj:"Hifu"},
            // Colors
            {jp:"赤", en:"Red", rj:"Aka"}, {jp:"青", en:"Blue", rj:"Ao"}, {jp:"白", en:"White", rj:"Shiro"},
            {jp:"黒", en:"Black", rj:"Kuro"}, {jp:"緑", en:"Green", rj:"Midori"}, {jp:"黄色", en:"Yellow", rj:"Kiiro"},
            {jp:"茶色", en:"Brown", rj:"Chairo"}, {jp:"紫", en:"Purple", rj:"Murasaki"}, {jp:"橙", en:"Orange", rj:"Orenji"},
            {jp:"灰色", en:"Grey", rj:"Haiiro"}, {jp:"ピンク", en:"Pink", rj:"Pinku"},
            // Numbers
            {jp:"一", en:"One", rj:"Ichi"}, {jp:"二", en:"Two", rj:"Ni"}, {jp:"三", en:"Three", rj:"San"},
            {jp:"四", en:"Four", rj:"Shi/Yon"}, {jp:"五", en:"Five", rj:"Go"}, {jp:"六", en:"Six", rj:"Roku"},
            {jp:"七", en:"Seven", rj:"Nana/Shichi"}, {jp:"八", en:"Eight", rj:"Hachi"}, {jp:"九", en:"Nine", rj:"Ku/Kyuu"},
            {jp:"十", en:"Ten", rj:"Juu"}, {jp:"百", en:"Hundred", rj:"Hyaku"}, {jp:"千", en:"Thousand", rj:"Sen"},
            {jp:"万", en:"Ten thousand", rj:"Man"},
            // Family
            {jp:"母", en:"Mother", rj:"Haha"}, {jp:"父", en:"Father", rj:"Chichi"}, {jp:"兄", en:"Older brother", rj:"Ani"},
            {jp:"姉", en:"Older sister", rj:"Ane"}, {jp:"弟", en:"Younger brother", rj:"Otouto"}, {jp:"妹", en:"Younger sister", rj:"Imouto"},
            {jp:"子供", en:"Child", rj:"Kodomo"}, {jp:"祖父", en:"Grandfather", rj:"Sofu"}, {jp:"祖母", en:"Grandmother", rj:"Sobo"},
            {jp:"夫", en:"Husband", rj:"Otto"}, {jp:"妻", en:"Wife", rj:"Tsuma"},
            // Animals
            {jp:"馬", en:"Horse", rj:"Uma"}, {jp:"牛", en:"Cow", rj:"Ushi"}, {jp:"豚", en:"Pig", rj:"Buta"},
            {jp:"羊", en:"Sheep", rj:"Hitsuji"}, {jp:"兎", en:"Rabbit", rj:"Usagi"}, {jp:"象", en:"Elephant", rj:"Zou"},
            {jp:"虎", en:"Tiger", rj:"Tora"}, {jp:"熊", en:"Bear", rj:"Kuma"}, {jp:"猿", en:"Monkey", rj:"Saru"},
            {jp:"蛇", en:"Snake", rj:"Hebi"}, {jp:"蛙", en:"Frog", rj:"Kaeru"}, {jp:"虫", en:"Insect/Bug", rj:"Mushi"},
            // Food
            {jp:"ご飯", en:"Cooked rice/Meal", rj:"Gohan"}, {jp:"パン", en:"Bread", rj:"Pan"}, {jp:"麺", en:"Noodles", rj:"Men"},
            {jp:"豆腐", en:"Tofu", rj:"Toufu"}, {jp:"味噌", en:"Miso", rj:"Miso"}, {jp:"醤油", en:"Soy sauce", rj:"Shouyu"},
            {jp:"塩", en:"Salt", rj:"Shio"}, {jp:"砂糖", en:"Sugar", rj:"Satou"}, {jp:"酢", en:"Vinegar", rj:"Su"},
            {jp:"野菜", en:"Vegetables", rj:"Yasai"}, {jp:"果物", en:"Fruit", rj:"Kudamono"}, {jp:"牛乳", en:"Milk", rj:"Gyuunyuu"},
            {jp:"酒", en:"Sake/Alcohol", rj:"Sake"}, {jp:"水", en:"Water", rj:"Mizu"}, {jp:"コーヒー", en:"Coffee", rj:"Koohii"},
            // Nature & Weather
            {jp:"海", en:"Sea/Ocean", rj:"Umi"}, {jp:"空", en:"Sky", rj:"Sora"}, {jp:"星", en:"Star", rj:"Hoshi"},
            {jp:"石", en:"Stone/Rock", rj:"Ishi"}, {jp:"土地", en:"Land", rj:"Tochi"}, {jp:"森", en:"Forest", rj:"Mori"},
            {jp:"池", en:"Pond", rj:"Ike"}, {jp:"湖", en:"Lake", rj:"Mizuumi"}, {jp:"島", en:"Island", rj:"Shima"},
            {jp:"砂", en:"Sand", rj:"Suna"}, {jp:"雲", en:"Cloud", rj:"Kumo"}, {jp:"霧", en:"Fog/Mist", rj:"Kiri"},
            // Common adjectives (i-adjectives)
            {jp:"大きい", en:"Big", rj:"Ookii"}, {jp:"小さい", en:"Small", rj:"Chiisai"}, {jp:"新しい", en:"New", rj:"Atarashii"},
            {jp:"古い", en:"Old", rj:"Furui"}, {jp:"良い", en:"Good", rj:"Yoi/Ii"}, {jp:"悪い", en:"Bad", rj:"Warui"},
            {jp:"速い", en:"Fast", rj:"Hayai"}, {jp:"遅い", en:"Slow/Late", rj:"Osoi"}, {jp:"熱い", en:"Hot", rj:"Atsui"},
            {jp:"冷たい", en:"Cold (to touch)", rj:"Tsumetai"}, {jp:"寒い", en:"Cold (weather)", rj:"Samui"}, {jp:"暑い", en:"Hot (weather)", rj:"Atsui"},
            {jp:"長い", en:"Long", rj:"Nagai"}, {jp:"短い", en:"Short", rj:"Mijikai"}, {jp:"高い", en:"Tall/Expensive", rj:"Takai"},
            {jp:"安い", en:"Cheap", rj:"Yasui"}, {jp:"重い", en:"Heavy", rj:"Omoi"}, {jp:"軽い", en:"Light (weight)", rj:"Karui"},
            {jp:"強い", en:"Strong", rj:"Tsuyoi"}, {jp:"弱い", en:"Weak", rj:"Yowai"},
            // Days & Time
            {jp:"今日", en:"Today", rj:"Kyou"}, {jp:"明日", en:"Tomorrow", rj:"Ashita"}, {jp:"昨日", en:"Yesterday", rj:"Kinou"},
            {jp:"朝", en:"Morning", rj:"Asa"}, {jp:"昼", en:"Noon/Daytime", rj:"Hiru"}, {jp:"夜", en:"Night", rj:"Yoru"},
            {jp:"週", en:"Week", rj:"Shuu"}, {jp:"年", en:"Year", rj:"Toshi/Nen"}, {jp:"春", en:"Spring", rj:"Haru"},
            {jp:"夏", en:"Summer", rj:"Natsu"}, {jp:"秋", en:"Autumn", rj:"Aki"}, {jp:"冬", en:"Winter", rj:"Fuyu"},
            // Places
            {jp:"家", en:"House/Home", rj:"Ie/Uchi"}, {jp:"店", en:"Shop/Store", rj:"Mise"}, {jp:"駅", en:"Station", rj:"Eki"},
            {jp:"道", en:"Road/Way", rj:"Michi"}, {jp:"橋", en:"Bridge", rj:"Hashi"}, {jp:"公園", en:"Park", rj:"Kouen"},
            {jp:"病院", en:"Hospital", rj:"Byouin"}, {jp:"空港", en:"Airport", rj:"Kuukou"},
        ],
        medium: [
            // Original entries
            {jp:"食べる", en:"To eat", rj:"Taberu"}, {jp:"飲む", en:"To drink", rj:"Nomu"},
            {jp:"見る", en:"To see", rj:"Miru"}, {jp:"聞く", en:"To listen", rj:"Kiku"},
            {jp:"書く", en:"To write", rj:"Kaku"}, {jp:"読む", en:"To read", rj:"Yomu"},
            {jp:"歩く", en:"To walk", rj:"Aruku"}, {jp:"走る", en:"To run", rj:"Hashiru"},
            {jp:"先生", en:"Teacher", rj:"Sensei"}, {jp:"学生", en:"Student", rj:"Gakusei"},
            {jp:"学校", en:"School", rj:"Gakkou"}, {jp:"友達", en:"Friend", rj:"Tomodachi"},
            {jp:"家族", en:"Family", rj:"Kazoku"}, {jp:"料理", en:"Cooking", rj:"Ryouri"},
            {jp:"時間", en:"Time", rj:"Jikan"}, {jp:"電話", en:"Phone", rj:"Denwa"},
            {jp:"切符", en:"Ticket", rj:"Kippu"}, {jp:"荷物", en:"Luggage", rj:"Nimotsu"},
            // NEW medium words — Verbs
            {jp:"話す", en:"To speak", rj:"Hanasu"}, {jp:"来る", en:"To come", rj:"Kuru"},
            {jp:"行く", en:"To go", rj:"Iku"}, {jp:"帰る", en:"To return home", rj:"Kaeru"},
            {jp:"起きる", en:"To wake up", rj:"Okiru"}, {jp:"寝る", en:"To sleep", rj:"Neru"},
            {jp:"座る", en:"To sit", rj:"Suwaru"}, {jp:"立つ", en:"To stand", rj:"Tatsu"},
            {jp:"使う", en:"To use", rj:"Tsukau"}, {jp:"作る", en:"To make/create", rj:"Tsukuru"},
            {jp:"買う", en:"To buy", rj:"Kau"}, {jp:"売る", en:"To sell", rj:"Uru"},
            {jp:"持つ", en:"To hold/have", rj:"Motsu"}, {jp:"待つ", en:"To wait", rj:"Matsu"},
            {jp:"会う", en:"To meet", rj:"Au"}, {jp:"知る", en:"To know", rj:"Shiru"},
            {jp:"思う", en:"To think/feel", rj:"Omou"}, {jp:"言う", en:"To say", rj:"Iu"},
            {jp:"聞こえる", en:"To be audible", rj:"Kikoeru"}, {jp:"見える", en:"To be visible", rj:"Mieru"},
            {jp:"開ける", en:"To open", rj:"Akeru"}, {jp:"閉める", en:"To close", rj:"Shimeru"},
            {jp:"始める", en:"To begin", rj:"Hajimeru"}, {jp:"終わる", en:"To end/finish", rj:"Owaru"},
            {jp:"変える", en:"To change", rj:"Kaeru"}, {jp:"教える", en:"To teach", rj:"Oshieru"},
            {jp:"習う", en:"To learn", rj:"Narau"}, {jp:"覚える", en:"To memorise", rj:"Oboeru"},
            {jp:"忘れる", en:"To forget", rj:"Wasureru"}, {jp:"助ける", en:"To help", rj:"Tasukeru"},
            {jp:"貸す", en:"To lend", rj:"Kasu"}, {jp:"借りる", en:"To borrow", rj:"Kariru"},
            {jp:"送る", en:"To send", rj:"Okuru"}, {jp:"受ける", en:"To receive", rj:"Ukeru"},
            {jp:"選ぶ", en:"To choose", rj:"Erabu"}, {jp:"決める", en:"To decide", rj:"Kimeru"},
            {jp:"考える", en:"To think/consider", rj:"Kangaeru"}, {jp:"感じる", en:"To feel/sense", rj:"Kanjiru"},
            {jp:"続ける", en:"To continue", rj:"Tsuzukeru"}, {jp:"止まる", en:"To stop", rj:"Tomaru"},
            // Nouns — Daily life
            {jp:"仕事", en:"Work/Job", rj:"Shigoto"}, {jp:"会社", en:"Company", rj:"Kaisha"},
            {jp:"部屋", en:"Room", rj:"Heya"}, {jp:"窓", en:"Window", rj:"Mado"},
            {jp:"椅子", en:"Chair", rj:"Isu"}, {jp:"机", en:"Desk/Table", rj:"Tsukue"},
            {jp:"本", en:"Book", rj:"Hon"}, {jp:"新聞", en:"Newspaper", rj:"Shinbun"},
            {jp:"雑誌", en:"Magazine", rj:"Zasshi"}, {jp:"ペン", en:"Pen", rj:"Pen"},
            {jp:"鞄", en:"Bag", rj:"Kaban"}, {jp:"財布", en:"Wallet", rj:"Saifu"},
            {jp:"鍵", en:"Key", rj:"Kagi"}, {jp:"時計", en:"Clock/Watch", rj:"Tokei"},
            {jp:"眼鏡", en:"Glasses", rj:"Megane"}, {jp:"傘", en:"Umbrella", rj:"Kasa"},
            {jp:"服", en:"Clothes", rj:"Fuku"}, {jp:"靴", en:"Shoes", rj:"Kutsu"},
            {jp:"帽子", en:"Hat/Cap", rj:"Boushi"}, {jp:"薬", en:"Medicine", rj:"Kusuri"},
            // Transport & City
            {jp:"電車", en:"Train", rj:"Densha"}, {jp:"バス", en:"Bus", rj:"Basu"},
            {jp:"飛行機", en:"Airplane", rj:"Hikouki"}, {jp:"船", en:"Ship/Boat", rj:"Fune"},
            {jp:"タクシー", en:"Taxi", rj:"Takushii"}, {jp:"地下鉄", en:"Subway", rj:"Chikatetsu"},
            {jp:"信号", en:"Traffic light", rj:"Shingou"}, {jp:"交差点", en:"Intersection", rj:"Kousaten"},
            {jp:"地図", en:"Map", rj:"Chizu"}, {jp:"入口", en:"Entrance", rj:"Iriguchi"},
            {jp:"出口", en:"Exit", rj:"Deguchi"}, {jp:"右", en:"Right", rj:"Migi"},
            {jp:"左", en:"Left", rj:"Hidari"}, {jp:"真っ直ぐ", en:"Straight ahead", rj:"Massugu"},
            // Na-adjectives & Descriptors
            {jp:"元気", en:"Healthy/Energetic", rj:"Genki"}, {jp:"静か", en:"Quiet", rj:"Shizuka"},
            {jp:"賑やか", en:"Lively/Bustling", rj:"Nigiyaka"}, {jp:"親切", en:"Kind", rj:"Shinsetsu"},
            {jp:"大切", en:"Important/Precious", rj:"Taisetsu"}, {jp:"素敵", en:"Lovely/Nice", rj:"Suteki"},
            {jp:"便利", en:"Convenient", rj:"Benri"}, {jp:"不便", en:"Inconvenient", rj:"Fuben"},
            {jp:"安全", en:"Safe", rj:"Anzen"}, {jp:"危険", en:"Dangerous", rj:"Kiken"},
            {jp:"有名", en:"Famous", rj:"Yuumei"}, {jp:"丈夫", en:"Sturdy/Durable", rj:"Joubu"},
            {jp:"大丈夫", en:"Okay/Fine", rj:"Daijoubu"}, {jp:"必要", en:"Necessary", rj:"Hitsuyou"},
            {jp:"自由", en:"Free/Freedom", rj:"Jiyuu"}, {jp:"簡単", en:"Easy/Simple", rj:"Kantan"},
            {jp:"難しい", en:"Difficult", rj:"Muzukashii"}, {jp:"楽しい", en:"Fun/Enjoyable", rj:"Tanoshii"},
            {jp:"嬉しい", en:"Happy/Glad", rj:"Ureshii"}, {jp:"悲しい", en:"Sad", rj:"Kanashii"},
            {jp:"怖い", en:"Scary", rj:"Kowai"}, {jp:"恥ずかしい", en:"Embarrassing", rj:"Hazukashii"},
            {jp:"面白い", en:"Interesting/Funny", rj:"Omoshiroi"}, {jp:"つまらない", en:"Boring", rj:"Tsumaranai"},
            // Meals & Food nouns
            {jp:"朝食", en:"Breakfast", rj:"Choushoku"}, {jp:"昼食", en:"Lunch", rj:"Chuushoku"},
            {jp:"夕食", en:"Dinner", rj:"Yuushoku"}, {jp:"おかず", en:"Side dish", rj:"Okazu"},
            {jp:"スープ", en:"Soup", rj:"Suupu"}, {jp:"ケーキ", en:"Cake", rj:"Keeki"},
            {jp:"アイスクリーム", en:"Ice cream", rj:"Aisu kuriimu"}, {jp:"りんご", en:"Apple", rj:"Ringo"},
            {jp:"みかん", en:"Mandarin/Tangerine", rj:"Mikan"}, {jp:"バナナ", en:"Banana", rj:"Banana"},
            {jp:"トマト", en:"Tomato", rj:"Tomato"}, {jp:"にんじん", en:"Carrot", rj:"Ninjin"},
            {jp:"玉ねぎ", en:"Onion", rj:"Tamanegi"}, {jp:"じゃがいも", en:"Potato", rj:"Jagaimo"},
            {jp:"レストラン", en:"Restaurant", rj:"Resutoran"}, {jp:"メニュー", en:"Menu", rj:"Menyuu"},
        ],
        hard: [
            // Original entries
            {jp:"図書館", en:"Library", rj:"Toshokan"}, {jp:"自転車", en:"Bicycle", rj:"Jitensha"},
            {jp:"自動車", en:"Car", rj:"Jidousha"}, {jp:"郵便局", en:"Post Office", rj:"Yuubinkyoku"},
            {jp:"経済", en:"Economy", rj:"Keizai"}, {jp:"政治", en:"Politics", rj:"Seiji"},
            {jp:"環境", en:"Environment", rj:"Kankyou"}, {jp:"法律", en:"Law", rj:"Houritsu"},
            {jp:"歴史", en:"History", rj:"Rekishi"}, {jp:"複雑", en:"Complex", rj:"Fukuzatsu"},
            {jp:"準備", en:"Preparation", rj:"Junbi"}, {jp:"経験", en:"Experience", rj:"Keiken"},
            // NEW hard words — Abstract & Academic
            {jp:"社会", en:"Society", rj:"Shakai"}, {jp:"文化", en:"Culture", rj:"Bunka"},
            {jp:"科学", en:"Science", rj:"Kagaku"}, {jp:"技術", en:"Technology/Skill", rj:"Gijutsu"},
            {jp:"哲学", en:"Philosophy", rj:"Tetsugaku"}, {jp:"芸術", en:"Art", rj:"Geijutsu"},
            {jp:"宗教", en:"Religion", rj:"Shuukyou"}, {jp:"心理", en:"Psychology/Mentality", rj:"Shinri"},
            {jp:"医学", en:"Medical science", rj:"Igaku"}, {jp:"物理", en:"Physics", rj:"Butsuri"},
            {jp:"化学", en:"Chemistry", rj:"Kagaku"}, {jp:"数学", en:"Mathematics", rj:"Suugaku"},
            {jp:"文学", en:"Literature", rj:"Bungaku"}, {jp:"音楽", en:"Music", rj:"Ongaku"},
            {jp:"建築", en:"Architecture", rj:"Kenchiku"}, {jp:"農業", en:"Agriculture", rj:"Nougyou"},
            {jp:"工業", en:"Industry", rj:"Kougyou"}, {jp:"商業", en:"Commerce", rj:"Shougyou"},
            {jp:"教育", en:"Education", rj:"Kyouiku"}, {jp:"研究", en:"Research", rj:"Kenkyuu"},
            {jp:"発展", en:"Development/Growth", rj:"Hatten"}, {jp:"成長", en:"Growth/Maturation", rj:"Seichou"},
            {jp:"変化", en:"Change", rj:"Henka"}, {jp:"影響", en:"Influence/Effect", rj:"Eikyou"},
            {jp:"問題", en:"Problem/Issue", rj:"Mondai"}, {jp:"解決", en:"Solution/Resolution", rj:"Kaiketsu"},
            {jp:"結果", en:"Result/Outcome", rj:"Kekka"}, {jp:"原因", en:"Cause/Reason", rj:"Genin"},
            {jp:"目的", en:"Purpose/Goal", rj:"Mokuteki"}, {jp:"方法", en:"Method/Way", rj:"Houhou"},
            {jp:"状況", en:"Situation/Condition", rj:"Joukyou"}, {jp:"理由", en:"Reason", rj:"Riyuu"},
            {jp:"関係", en:"Relationship/Connection", rj:"Kankei"}, {jp:"立場", en:"Position/Standpoint", rj:"Tachiba"},
            {jp:"責任", en:"Responsibility", rj:"Sekinin"}, {jp:"義務", en:"Duty/Obligation", rj:"Gimu"},
            {jp:"権利", en:"Right/Privilege", rj:"Kenri"}, {jp:"機会", en:"Opportunity/Chance", rj:"Kikai"},
            // Complex verbs
            {jp:"理解する", en:"To understand", rj:"Rikai suru"}, {jp:"説明する", en:"To explain", rj:"Setsumei suru"},
            {jp:"確認する", en:"To confirm/check", rj:"Kakunin suru"}, {jp:"紹介する", en:"To introduce", rj:"Shoukai suru"},
            {jp:"参加する", en:"To participate", rj:"Sanka suru"}, {jp:"利用する", en:"To use/utilise", rj:"Riyou suru"},
            {jp:"判断する", en:"To judge/decide", rj:"Handan suru"}, {jp:"比較する", en:"To compare", rj:"Hikaku suru"},
            {jp:"表現する", en:"To express", rj:"Hyougen suru"}, {jp:"反省する", en:"To reflect/regret", rj:"Hansei suru"},
            {jp:"注意する", en:"To be careful/warn", rj:"Chuui suru"}, {jp:"心配する", en:"To worry", rj:"Shinpai suru"},
            {jp:"集中する", en:"To concentrate", rj:"Shuuchuu suru"}, {jp:"努力する", en:"To make an effort", rj:"Doryoku suru"},
            {jp:"失敗する", en:"To fail", rj:"Shippai suru"}, {jp:"成功する", en:"To succeed", rj:"Seikou suru"},
            {jp:"経験する", en:"To experience", rj:"Keiken suru"}, {jp:"想像する", en:"To imagine", rj:"Souzou suru"},
            // Hard adjectives
            {jp:"複雑な", en:"Complicated", rj:"Fukuzatsu na"}, {jp:"正確な", en:"Accurate/Precise", rj:"Seikaku na"},
            {jp:"適切な", en:"Appropriate", rj:"Tekisetsu na"}, {jp:"具体的な", en:"Concrete/Specific", rj:"Gutaiteki na"},
            {jp:"抽象的な", en:"Abstract", rj:"Chuushouteki na"}, {jp:"積極的な", en:"Proactive/Positive", rj:"Sekkyokuteki na"},
            {jp:"消極的な", en:"Passive/Negative", rj:"Shoukyokuteki na"}, {jp:"感情的な", en:"Emotional", rj:"Kanjouteki na"},
            {jp:"論理的な", en:"Logical", rj:"Ronriteki na"}, {jp:"現実的な", en:"Realistic", rj:"Genjitsuteki na"},
        ],
        vhard: [
            // Original entries
            {jp:"一生懸命", en:"With all one's effort", rj:"Isshoukenmei"},
            {jp:"試行錯誤", en:"Trial and Error", rj:"Shikousakugo"},
            {jp:"興味津々", en:"Very interested", rj:"Kyoumishinshin"},
            {jp:"弱肉強食", en:"Survival of the fittest", rj:"Jakunikukyoushoku"},
            {jp:"以心伝心", en:"Telepathy/Communication without words", rj:"Ishindenshin"},
            {jp:"温故知新", en:"Learning from the past", rj:"Onkochishin"},
            {jp:"一期一会", en:"Once in a lifetime encounter", rj:"Ichigoichie"},
            // NEW vhard words — Yojijukugo (four-character idioms)
            {jp:"七転八起", en:"Fall seven times, get up eight (perseverance)", rj:"Shichitenhakki"},
            {jp:"自業自得", en:"Reaping what you sow", rj:"Jigoujitoку"},
            {jp:"臨機応変", en:"Adapting to circumstances", rj:"Rinkiouhen"},
            {jp:"初志貫徹", en:"Carrying out one's original intentions", rj:"Shoshikanttetsu"},
            {jp:"十人十色", en:"Different strokes for different folks", rj:"Juunintoiro"},
            {jp:"馬耳東風", en:"Turning a deaf ear (lit: east wind in a horse's ear)", rj:"Bajitoufu"},
            {jp:"付和雷同", en:"Going along with the crowd", rj:"Fuwaraidou"},
            {jp:"大器晩成", en:"Late bloomer (great talents mature late)", rj:"Taikibansei"},
            {jp:"起死回生", en:"Comeback from the brink", rj:"Kishikaisei"},
            {jp:"切磋琢磨", en:"Mutual improvement through competition", rj:"Sessatakuma"},
            {jp:"千載一遇", en:"A once-in-a-thousand-years opportunity", rj:"Senzaiichiguu"},
            {jp:"針小棒大", en:"Making a mountain out of a molehill", rj:"Shinshoboudai"},
            {jp:"五里霧中", en:"Being completely lost/in the dark", rj:"Gorimuchuu"},
            {jp:"四苦八苦", en:"Struggling with great difficulties", rj:"Shikuhakku"},
            {jp:"天下泰平", en:"World at peace/All is well", rj:"Tenkataihei"},
            {jp:"無我夢中", en:"Being absorbed in something, forgetting oneself", rj:"Mugamuchuu"},
            {jp:"表裏一体", en:"Two sides of the same coin", rj:"Hyouriittai"},
            {jp:"言語道断", en:"Outrageous/Beyond words", rj:"Gongodoudan"},
            {jp:"主客転倒", en:"Putting the cart before the horse", rj:"Shukyakutentou"},
            {jp:"心機一転", en:"Making a fresh start", rj:"Shinkiiitten"},
            {jp:"我田引水", en:"Drawing water to one's own field (self-serving)", rj:"Gatenninsui"},
        ]
    },
    phrases: {
        easy: [
            // Original entry
            {jp:"はじめまして", en:"Nice to meet you", rj:"Hajimemashite"},
            // NEW easy phrases
            {jp:"おはようございます", en:"Good morning (formal)", rj:"Ohayou gozaimasu"},
            {jp:"おはよう", en:"Good morning (casual)", rj:"Ohayou"},
            {jp:"こんにちは", en:"Good afternoon/Hello", rj:"Konnichiwa"},
            {jp:"こんばんは", en:"Good evening", rj:"Konbanwa"},
            {jp:"おやすみなさい", en:"Good night", rj:"Oyasuminasai"},
            {jp:"ありがとうございます", en:"Thank you very much", rj:"Arigatou gozaimasu"},
            {jp:"ありがとう", en:"Thank you (casual)", rj:"Arigatou"},
            {jp:"どういたしまして", en:"You're welcome", rj:"Dou itashimashite"},
            {jp:"すみません", en:"Excuse me/Sorry", rj:"Sumimasen"},
            {jp:"ごめんなさい", en:"I'm sorry", rj:"Gomen nasai"},
            {jp:"はい", en:"Yes", rj:"Hai"},
            {jp:"いいえ", en:"No", rj:"Iie"},
            {jp:"わかりました", en:"I understand/Got it", rj:"Wakarimashita"},
            {jp:"わかりません", en:"I don't understand", rj:"Wakarimasen"},
            {jp:"お名前は？", en:"What is your name?", rj:"Onamae wa?"},
            {jp:"私の名前は〜です", en:"My name is ~", rj:"Watashi no namae wa ~ desu"},
            {jp:"お元気ですか？", en:"How are you?", rj:"Ogenki desu ka?"},
            {jp:"元気です", en:"I'm fine", rj:"Genki desu"},
            {jp:"どこから来ましたか？", en:"Where are you from?", rj:"Doko kara kimashita ka?"},
            {jp:"〜から来ました", en:"I'm from ~", rj:"~ kara kimashita"},
            {jp:"さようなら", en:"Goodbye (formal)", rj:"Sayounara"},
            {jp:"じゃあね", en:"See ya (casual)", rj:"Jaa ne"},
            {jp:"いただきます", en:"Let's eat (before meal)", rj:"Itadakimasu"},
            {jp:"ごちそうさまでした", en:"That was delicious (after meal)", rj:"Gochisousama deshita"},
            {jp:"おねがいします", en:"Please (requesting)", rj:"Onegai shimasu"},
            {jp:"〜はどこですか？", en:"Where is ~?", rj:"~ wa doko desu ka?"},
            {jp:"いくらですか？", en:"How much is it?", rj:"Ikura desu ka?"},
            {jp:"何時ですか？", en:"What time is it?", rj:"Nanji desu ka?"},
            {jp:"大丈夫です", en:"I'm okay/It's fine", rj:"Daijoubu desu"},
            {jp:"少し話せます", en:"I can speak a little", rj:"Sukoshi hanasemasu"},
            {jp:"ゆっくり話してください", en:"Please speak slowly", rj:"Yukkuri hanashite kudasai"},
            {jp:"もう一度言ってください", en:"Please say it again", rj:"Mou ichido itte kudasai"},
            {jp:"トイレはどこですか？", en:"Where is the toilet?", rj:"Toire wa doko desu ka?"},
            {jp:"助けてください", en:"Please help me", rj:"Tasukete kudasai"},
        ],
        medium: [
            {jp:"日本語を勉強しています", en:"I am studying Japanese", rj:"Nihongo wo benkyou shite imasu"},
            {jp:"もっとゆっくり話せますか？", en:"Can you speak more slowly?", rj:"Motto yukkuri hanasemasu ka?"},
            {jp:"これは何ですか？", en:"What is this?", rj:"Kore wa nan desu ka?"},
            {jp:"どうやって行きますか？", en:"How do I get there?", rj:"Dou yatte ikimasu ka?"},
            {jp:"〜をください", en:"Please give me ~", rj:"~ wo kudasai"},
            {jp:"〜が好きです", en:"I like ~", rj:"~ ga suki desu"},
            {jp:"〜が嫌いです", en:"I dislike ~", rj:"~ ga kirai desu"},
            {jp:"〜を食べたことがあります", en:"I have eaten ~ before", rj:"~ wo tabeta koto ga arimasu"},
            {jp:"電車は何時に来ますか？", en:"What time does the train come?", rj:"Densha wa nanji ni kimasu ka?"},
            {jp:"予約したいのですが", en:"I would like to make a reservation", rj:"Yoyaku shitai no desu ga"},
            {jp:"これはどういう意味ですか？", en:"What does this mean?", rj:"Kore wa dou iu imi desu ka?"},
            {jp:"どのくらいかかりますか？", en:"How long will it take?", rj:"Dono kurai kakarimasu ka?"},
            {jp:"お会計をお願いします", en:"Check/Bill please", rj:"Okaikei wo onegai shimasu"},
            {jp:"写真を撮ってもいいですか？", en:"May I take a photo?", rj:"Shashin wo totte mo ii desu ka?"},
            {jp:"〜はありますか？", en:"Do you have ~?", rj:"~ wa arimasu ka?"},
            {jp:"今日は天気がいいですね", en:"The weather is nice today, isn't it?", rj:"Kyou wa tenki ga ii desu ne"},
            {jp:"一緒に行きませんか？", en:"Would you like to go together?", rj:"Issho ni ikimasen ka?"},
            {jp:"何が食べたいですか？", en:"What do you want to eat?", rj:"Nani ga tabetai desu ka?"},
            {jp:"お腹が空きました", en:"I'm hungry", rj:"Onaka ga sukimashita"},
            {jp:"疲れました", en:"I'm tired", rj:"Tsukaremashita"},
            {jp:"頭が痛いです", en:"I have a headache", rj:"Atama ga itai desu"},
            {jp:"日本はどうですか？", en:"How is Japan?", rj:"Nihon wa dou desu ka?"},
            {jp:"趣味は何ですか？", en:"What are your hobbies?", rj:"Shumi wa nan desu ka?"},
            {jp:"仕事は何ですか？", en:"What is your job?", rj:"Shigoto wa nan desu ka?"},
            {jp:"週末に何をしますか？", en:"What do you do on weekends?", rj:"Shuumatsu ni nani wo shimasu ka?"},
            {jp:"どこに住んでいますか？", en:"Where do you live?", rj:"Doko ni sunde imasu ka?"},
            {jp:"日本料理が大好きです", en:"I love Japanese food", rj:"Nihon ryouri ga daisuki desu"},
            {jp:"もう少し待ってください", en:"Please wait a little more", rj:"Mou sukoshi matte kudasai"},
            {jp:"問題ありません", en:"No problem", rj:"Mondai arimasen"},
            {jp:"気をつけてください", en:"Please be careful/Take care", rj:"Ki wo tsukete kudasai"},
            {jp:"お世話になっています", en:"Thank you for your support (business/polite)", rj:"Osewa ni natte imasu"},
            {jp:"よろしくお願いします", en:"Please treat me well/I'm counting on you", rj:"Yoroshiku onegai shimasu"},
            {jp:"ちょっと待ってください", en:"Please wait a moment", rj:"Chotto matte kudasai"},
            {jp:"どちらでもいいです", en:"Either is fine", rj:"Dochira demo ii desu"},
            {jp:"それはいい考えですね", en:"That's a good idea", rj:"Sore wa ii kangae desu ne"},
            {jp:"本当ですか？", en:"Really? Is that true?", rj:"Hontou desu ka?"},
            {jp:"そうですね", en:"That's right/I see", rj:"Sou desu ne"},
            {jp:"なるほど", en:"I see/That makes sense", rj:"Naruhodo"},
            {jp:"おめでとうございます", en:"Congratulations", rj:"Omedetou gozaimasu"},
            {jp:"お誕生日おめでとう", en:"Happy birthday", rj:"Otanjoubi omedetou"},
            {jp:"ご苦労様でした", en:"Thank you for your hard work", rj:"Gokurousama deshita"},
            {jp:"お疲れ様でした", en:"Good work/You've worked hard", rj:"Otsukaresama deshita"},
            {jp:"失礼します", en:"Excuse me (entering/leaving)", rj:"Shitsurei shimasu"},
        ],
        hard: [
            {jp:"もし〜なら、〜でしょう", en:"If ~ then it would be ~", rj:"Moshi ~ nara, ~ deshou"},
            {jp:"〜にもかかわらず、〜", en:"Despite ~, ~", rj:"~ ni mo kakawarazu, ~"},
            {jp:"それはともかくとして", en:"Setting that aside", rj:"Sore wa tomokaku toshite"},
            {jp:"〜というわけではありません", en:"That doesn't mean ~", rj:"~ to iu wake de wa arimasen"},
            {jp:"考えれば考えるほど複雑になる", en:"The more I think, the more complex it becomes", rj:"Kangaereba kangaeru hodo fukuzatsu ni naru"},
            {jp:"経験から学ぶことが大切だと思います", en:"I think it's important to learn from experience", rj:"Keiken kara manabu koto ga taisetsu da to omoimasu"},
            {jp:"文化の違いを理解することが重要です", en:"Understanding cultural differences is important", rj:"Bunka no chigai wo rikai suru koto ga juuyou desu"},
            {jp:"賛否両論あることは承知しています", en:"I'm aware there are arguments for and against", rj:"Sanpi ryouron aru koto wa shouchi shite imasu"},
            {jp:"一概には言えませんが", en:"It's hard to generalise, but...", rj:"Ichigai ni wa iemasen ga"},
            {jp:"それはケースバイケースです", en:"That is case by case", rj:"Sore wa keesu bai keesu desu"},
        ],
        vhard: [
            // Original entry
            {jp:"猿も木から落ちる", en:"Even monkeys fall from trees (everyone makes mistakes)", rj:"Saru mo ki kara ochiru"},
            // NEW vhard phrases — Proverbs & Idioms
            {jp:"七転び八起き", en:"Fall down seven times, stand up eight", rj:"Nana korobi ya oki"},
            {jp:"石の上にも三年", en:"Perseverance pays off (lit: three years on a stone)", rj:"Ishi no ue ni mo san nen"},
            {jp:"百聞は一見に如かず", en:"Seeing is believing (lit: hearing a hundred times is not as good as seeing once)", rj:"Hyakubun wa ikken ni shikazu"},
            {jp:"急がば回れ", en:"More haste less speed (lit: if in a hurry, go around)", rj:"Isogaba maware"},
            {jp:"花より団子", en:"Preferring the practical over the aesthetic (lit: dango over flowers)", rj:"Hana yori dango"},
            {jp:"出る杭は打たれる", en:"The nail that sticks up gets hammered down", rj:"Deru kui wa utareru"},
            {jp:"井の中の蛙大海を知らず", en:"The frog in the well knows nothing of the ocean", rj:"I no naka no kawazu taikai wo shirazu"},
            {jp:"能ある鷹は爪を隠す", en:"The skilled hawk hides its talons (humility)", rj:"Nou aru taka wa tsume wo kakusu"},
            {jp:"七つの海を渡る", en:"To travel the world (lit: cross seven seas)", rj:"Nanatsu no umi wo wataru"},
            {jp:"口は禍の門", en:"The mouth is the gate of misfortune", rj:"Kuchi wa wazawai no kado"},
            {jp:"笑う門には福来る", en:"Laughter brings good fortune", rj:"Warau kado ni wa fuku kitaru"},
            {jp:"時は金なり", en:"Time is money", rj:"Toki wa kane nari"},
            {jp:"塵も積もれば山となる", en:"Many small things add up (lit: even dust piled up becomes a mountain)", rj:"Chiri mo tsumoreba yama to naru"},
            {jp:"知らぬが仏", en:"Ignorance is bliss (lit: not knowing is Buddha)", rj:"Shiranu ga hotoke"},
            {jp:"泣きっ面に蜂", en:"Adding insult to injury (lit: a bee on a crying face)", rj:"Nakitttsura ni hachi"},
            {jp:"案ずるより産むが易し", en:"It's easier done than feared (lit: giving birth is easier than worrying)", rj:"Anzuru yori umu ga yasushi"},
            {jp:"触らぬ神に祟りなし", en:"Let sleeping dogs lie (lit: don't touch gods who don't curse you)", rj:"Sawaranu kami ni tatari nashi"},
        ]
    }
};