const PORTUGUESE_LIBRARY = {
    words: {
        easy: [
            // Original entries
            {pt:"Mão", en:"Hand", ph:"Mowm"}, {pt:"Pé", en:"Foot", ph:"Peh"}, {pt:"Sol", en:"Sun", ph:"Sol"},
            {pt:"Lua", en:"Moon", ph:"Loo-ah"}, {pt:"Cão", en:"Dog", ph:"Kowm"}, {pt:"Mar", en:"Sea", ph:"Mar"},
            {pt:"Rio", en:"River", ph:"Hee-o"}, {pt:"Flor", en:"Flower", ph:"Flor"}, {pt:"Casa", en:"House", ph:"Ca-za"},
            {pt:"Livro", en:"Book", ph:"Lee-vro"}, {pt:"Mesa", en:"Table", ph:"Me-za"}, {pt:"Pão", en:"Bread", ph:"Powm"},
            {pt:"Leite", en:"Milk", ph:"Ley-chee"}, {pt:"Água", en:"Water", ph:"Ah-gwa"}, {pt:"Amigo", en:"Friend", ph:"A-mee-go"},
            {pt:"Escola", en:"School", ph:"Es-co-la"}, {pt:"Carro", en:"Car", ph:"Ka-ho"}, {pt:"Rua", en:"Street", ph:"Hoo-ah"},
            {pt:"Porta", en:"Door", ph:"Por-ta"}, {pt:"Noite", en:"Night", ph:"Noy-chee"}, {pt:"Dia", en:"Day", ph:"Jee-a"},
            {pt:"Feliz", en:"Happy", ph:"Fe-leez"}, {pt:"Bom", en:"Good", ph:"Boh-m"}, {pt:"Amor", en:"Love", ph:"A-mor"},
            {pt:"Tempo", en:"Time", ph:"Tem-po"}, {pt:"Fruta", en:"Fruit", ph:"Froo-ta"}, {pt:"Cidade", en:"City", ph:"See-da-jee"},
            {pt:"Gato", en:"Cat", ph:"Ga-to"}, {pt:"Peixe", en:"Fish", ph:"Pay-shee"}, {pt:"Roupa", en:"Clothes", ph:"Ho-pa"},
            // NEW easy words — Body parts
            {pt:"Cabeça", en:"Head", ph:"Ca-be-sa"}, {pt:"Olho", en:"Eye", ph:"O-lyo"}, {pt:"Nariz", en:"Nose", ph:"Na-reez"},
            {pt:"Boca", en:"Mouth", ph:"Bo-ca"}, {pt:"Orelha", en:"Ear", ph:"O-re-lya"}, {pt:"Braço", en:"Arm", ph:"Bra-so"},
            {pt:"Perna", en:"Leg", ph:"Per-na"}, {pt:"Dedo", en:"Finger/Toe", ph:"De-do"}, {pt:"Costas", en:"Back", ph:"Cos-tas"},
            {pt:"Barriga", en:"Belly", ph:"Ba-hee-ga"},
            // Colors
            {pt:"Vermelho", en:"Red", ph:"Ver-me-lyo"}, {pt:"Azul", en:"Blue", ph:"A-zool"}, {pt:"Verde", en:"Green", ph:"Ver-jee"},
            {pt:"Amarelo", en:"Yellow", ph:"A-ma-re-lo"}, {pt:"Branco", en:"White", ph:"Bran-co"}, {pt:"Preto", en:"Black", ph:"Pre-to"},
            {pt:"Rosa", en:"Pink", ph:"Ho-za"}, {pt:"Laranja", en:"Orange", ph:"La-ran-zha"}, {pt:"Roxo", en:"Purple", ph:"Ho-sho"},
            {pt:"Cinza", en:"Grey", ph:"Seen-za"},
            // More Colors
            {pt:"Marrom", en:"Brown", ph:"Ma-hom"}, {pt:"Bege", en:"Beige", ph:"Be-zhee"}, {pt:"Turquesa", en:"Turquoise", ph:"Tur-ke-za"},
            {pt:"Dourado", en:"Gold", ph:"Do-ra-do"}, {pt:"Prateado", en:"Silver", ph:"Pra-chee-a-do"}, {pt:"Bordô", en:"Burgundy", ph:"Bor-doh"},
            {pt:"Lilás", en:"Lilac", ph:"Lee-las"}, {pt:"Creme", en:"Cream", ph:"Creh-mee"}, {pt:"Magenta", en:"Magenta", ph:"Ma-zhen-ta"},
            {pt:"Coral", en:"Coral", ph:"Co-ral"},
            // Numbers 1–10
            {pt:"Um", en:"One", ph:"Oong"}, {pt:"Dois", en:"Two", ph:"Doys"}, {pt:"Três", en:"Three", ph:"Tresh"},
            {pt:"Quatro", en:"Four", ph:"Kwa-tro"}, {pt:"Cinco", en:"Five", ph:"Seen-co"}, {pt:"Seis", en:"Six", ph:"Seys"},
            {pt:"Sete", en:"Seven", ph:"Se-chee"}, {pt:"Oito", en:"Eight", ph:"Oy-to"}, {pt:"Nove", en:"Nine", ph:"No-vee"},
            {pt:"Dez", en:"Ten", ph:"Desh"},
            // Numbers 11–20
            {pt:"Onze", en:"Eleven", ph:"On-zee"}, {pt:"Doze", en:"Twelve", ph:"Do-zee"}, {pt:"Treze", en:"Thirteen", ph:"Tre-zee"},
            {pt:"Catorze", en:"Fourteen", ph:"Ca-tor-zee"}, {pt:"Quinze", en:"Fifteen", ph:"Keen-zee"}, {pt:"Dezesseis", en:"Sixteen", ph:"De-ze-seys"},
            {pt:"Dezessete", en:"Seventeen", ph:"De-ze-se-chee"}, {pt:"Dezoito", en:"Eighteen", ph:"De-zoy-to"}, {pt:"Dezenove", en:"Nineteen", ph:"De-ze-no-vee"},
            {pt:"Vinte", en:"Twenty", ph:"Veen-chee"},
            // Numbers — Tens
            {pt:"Trinta", en:"Thirty", ph:"Treen-ta"}, {pt:"Quarenta", en:"Forty", ph:"Kwa-ren-ta"}, {pt:"Cinquenta", en:"Fifty", ph:"Seen-kwen-ta"},
            {pt:"Sessenta", en:"Sixty", ph:"Se-sen-ta"}, {pt:"Setenta", en:"Seventy", ph:"Se-ten-ta"}, {pt:"Oitenta", en:"Eighty", ph:"Oy-ten-ta"},
            {pt:"Noventa", en:"Ninety", ph:"No-ven-ta"}, {pt:"Cem", en:"One hundred", ph:"Sem"}, {pt:"Mil", en:"One thousand", ph:"Meel"},
            // Family
            {pt:"Mãe", en:"Mother", ph:"Mah-ee"}, {pt:"Pai", en:"Father", ph:"Pie"}, {pt:"Irmão", en:"Brother", ph:"Eer-mowm"},
            {pt:"Irmã", en:"Sister", ph:"Eer-mah"}, {pt:"Filho", en:"Son", ph:"Fee-lyo"}, {pt:"Filha", en:"Daughter", ph:"Fee-lya"},
            {pt:"Avô", en:"Grandfather", ph:"A-voh"}, {pt:"Avó", en:"Grandmother", ph:"A-vaw"}, {pt:"Tio", en:"Uncle", ph:"Chee-o"},
            {pt:"Tia", en:"Aunt", ph:"Chee-a"},
            // Animals
            {pt:"Pássaro", en:"Bird", ph:"Pa-sa-ro"}, {pt:"Cavalo", en:"Horse", ph:"Ca-va-lo"}, {pt:"Vaca", en:"Cow", ph:"Va-ca"},
            {pt:"Porco", en:"Pig", ph:"Por-co"}, {pt:"Galinha", en:"Chicken", ph:"Ga-leen-ya"}, {pt:"Coelho", en:"Rabbit", ph:"Co-e-lyo"},
            {pt:"Rato", en:"Mouse/Rat", ph:"Ha-to"}, {pt:"Leão", en:"Lion", ph:"Le-owm"}, {pt:"Tigre", en:"Tiger", ph:"Chee-gree"},
            {pt:"Elefante", en:"Elephant", ph:"E-le-fan-chee"},
            // Food & Drink
            {pt:"Arroz", en:"Rice", ph:"A-hosh"}, {pt:"Feijão", en:"Beans", ph:"Fey-zhowm"}, {pt:"Carne", en:"Meat", ph:"Car-nee"},
            {pt:"Frango", en:"Chicken (food)", ph:"Fran-go"}, {pt:"Ovo", en:"Egg", ph:"O-vo"}, {pt:"Queijo", en:"Cheese", ph:"Kay-zho"},
            {pt:"Sal", en:"Salt", ph:"Sal"}, {pt:"Açúcar", en:"Sugar", ph:"A-soo-car"}, {pt:"Café", en:"Coffee", ph:"Ca-feh"},
            {pt:"Suco", en:"Juice", ph:"Soo-co"},
            // Nature
            {pt:"Árvore", en:"Tree", ph:"Ar-vo-ree"}, {pt:"Montanha", en:"Mountain", ph:"Mon-tan-ya"}, {pt:"Chuva", en:"Rain", ph:"Shoo-va"},
            {pt:"Vento", en:"Wind", ph:"Ven-to"}, {pt:"Neve", en:"Snow", ph:"Ne-vee"}, {pt:"Fogo", en:"Fire", ph:"Fo-go"},
            {pt:"Terra", en:"Earth/Land", ph:"Te-ha"}, {pt:"Pedra", en:"Stone/Rock", ph:"Pe-dra"}, {pt:"Areia", en:"Sand", ph:"A-rey-a"},
            {pt:"Nuvem", en:"Cloud", ph:"Noo-vem"},
            // Common adjectives
            {pt:"Grande", en:"Big", ph:"Gran-jee"}, {pt:"Pequeno", en:"Small", ph:"Pe-ke-no"}, {pt:"Novo", en:"New", ph:"No-vo"},
            {pt:"Velho", en:"Old", ph:"Ve-lyo"}, {pt:"Bonito", en:"Beautiful", ph:"Bo-nee-to"}, {pt:"Feio", en:"Ugly", ph:"Fey-o"},
            {pt:"Rápido", en:"Fast", ph:"Ha-pee-do"}, {pt:"Lento", en:"Slow", ph:"Len-to"}, {pt:"Quente", en:"Hot", ph:"Ken-chee"},
            {pt:"Frio", en:"Cold", ph:"Free-o"},
            // Common verbs (infinitive)
            {pt:"Comer", en:"To eat", ph:"Co-mehr"}, {pt:"Beber", en:"To drink", ph:"Be-behr"}, {pt:"Dormir", en:"To sleep", ph:"Dor-meer"},
            {pt:"Correr", en:"To run", ph:"Co-hehr"}, {pt:"Andar", en:"To walk", ph:"An-dar"}, {pt:"Falar", en:"To speak", ph:"Fa-lar"},
            {pt:"Ouvir", en:"To hear/listen", ph:"O-veer"}, {pt:"Ver", en:"To see", ph:"Vehr"}, {pt:"Ler", en:"To read", ph:"Lehr"},
            {pt:"Escrever", en:"To write", ph:"Es-cre-vehr"},
            // Places
            {pt:"Banco", en:"Bank", ph:"Ban-co"}, {pt:"Mercado", en:"Market", ph:"Mer-ca-do"}, {pt:"Hospital", en:"Hospital", ph:"Os-pee-tal"},
            {pt:"Igreja", en:"Church", ph:"Ee-gre-zha"}, {pt:"Praia", en:"Beach", ph:"Pry-a"}, {pt:"Parque", en:"Park", ph:"Par-kee"},
            {pt:"Hotel", en:"Hotel", ph:"O-tel"}, {pt:"Aeroporto", en:"Airport", ph:"Ay-ro-por-to"},
        ],
        medium: [
            // Original entries
            {pt:"Cadeira", en:"Chair", ph:"Ca-dey-ra"}, {pt:"Janela", en:"Window", ph:"Ja-ne-la"},
            {pt:"Garrafa", en:"Bottle", ph:"Ga-ha-fa"}, {pt:"Sapato", en:"Shoe", ph:"Sa-pa-to"},
            {pt:"Caneta", en:"Pen", ph:"Ca-ne-ta"}, {pt:"Cozinha", en:"Kitchen", ph:"Co-zeen-ya"},
            {pt:"Abacaxi", en:"Pineapple", ph:"A-ba-ca-shee"}, {pt:"Relógio", en:"Clock", ph:"Re-lo-zhyo"},
            {pt:"Espelho", en:"Mirror", ph:"Es-pe-lyo"}, {pt:"Trabalho", en:"Work", ph:"Tra-ba-lyo"},
            {pt:"Viagem", en:"Trip", ph:"Vya-zhem"}, {pt:"Dinheiro", en:"Money", ph:"Jee-nyey-ro"},
            {pt:"Pescoço", en:"Neck", ph:"Pes-co-so"}, {pt:"Coração", en:"Heart", ph:"Co-ra-sowm"},
            {pt:"Amanhã", en:"Tomorrow", ph:"A-ma-nyah"}, {pt:"Bicicleta", en:"Bicycle", ph:"Bee-see-cle-ta"},
            {pt:"Presente", en:"Gift/Present", ph:"Pre-zen-chee"}, {pt:"Acreditar", en:"To believe", ph:"A-cre-jee-tar"},
            {pt:"Esquecer", en:"To forget", ph:"Es-ke-sehr"}, {pt:"Lembrar", en:"To remember", ph:"Lem-brar"},
            // NEW medium words — Verbs
            {pt:"Escolher", en:"To choose", ph:"Es-co-lyer"}, {pt:"Encontrar", en:"To find/meet", ph:"En-con-trar"},
            {pt:"Precisar", en:"To need", ph:"Pre-see-zar"}, {pt:"Conseguir", en:"To manage/get", ph:"Con-se-gheer"},
            {pt:"Perceber", en:"To understand/notice", ph:"Per-se-behr"}, {pt:"Conhecer", en:"To know (person)", ph:"Co-nye-sehr"},
            {pt:"Saber", en:"To know (fact)", ph:"Sa-behr"}, {pt:"Querer", en:"To want", ph:"Ke-rehr"},
            {pt:"Poder", en:"To be able to", ph:"Po-dehr"}, {pt:"Dever", en:"To owe/should", ph:"De-vehr"},
            {pt:"Trazer", en:"To bring", ph:"Tra-zehr"}, {pt:"Levar", en:"To take/carry", ph:"Le-var"},
            {pt:"Pedir", en:"To ask for", ph:"Pe-jeer"}, {pt:"Perguntar", en:"To ask (question)", ph:"Per-gun-tar"},
            {pt:"Responder", en:"To answer", ph:"Hes-pon-dehr"}, {pt:"Ajudar", en:"To help", ph:"A-zhoo-dar"},
            {pt:"Começar", en:"To begin", ph:"Co-me-sar"}, {pt:"Terminar", en:"To finish", ph:"Ter-mee-nar"},
            {pt:"Continuar", en:"To continue", ph:"Con-chee-noo-ar"}, {pt:"Parar", en:"To stop", ph:"Pa-rar"},
            {pt:"Mudar", en:"To change", ph:"Moo-dar"}, {pt:"Melhorar", en:"To improve", ph:"Me-lyo-rar"},
            {pt:"Perder", en:"To lose", ph:"Per-dehr"}, {pt:"Ganhar", en:"To win/earn", ph:"Ga-nyar"},
            {pt:"Tentar", en:"To try", ph:"Ten-tar"}, {pt:"Esperar", en:"To wait/hope", ph:"Es-pe-rar"},
            {pt:"Voltar", en:"To return", ph:"Vol-tar"}, {pt:"Sair", en:"To leave/go out", ph:"Sa-eer"},
            {pt:"Entrar", en:"To enter", ph:"En-trar"}, {pt:"Abrir", en:"To open", ph:"A-breer"},
            {pt:"Fechar", en:"To close", ph:"Fe-shar"}, {pt:"Comprar", en:"To buy", ph:"Com-prar"},
            {pt:"Vender", en:"To sell", ph:"Ven-dehr"}, {pt:"Pagar", en:"To pay", ph:"Pa-gar"},
            {pt:"Morar", en:"To live (reside)", ph:"Mo-rar"}, {pt:"Viajar", en:"To travel", ph:"Vya-zhar"},
            // Nouns — Home & Objects
            {pt:"Sofá", en:"Sofa/Couch", ph:"So-fa"}, {pt:"Cama", en:"Bed", ph:"Ca-ma"},
            {pt:"Travesseiro", en:"Pillow", ph:"Tra-ve-sey-ro"}, {pt:"Cobertor", en:"Blanket", ph:"Co-ber-tor"},
            {pt:"Armário", en:"Wardrobe/Cabinet", ph:"Ar-ma-ryo"}, {pt:"Gaveta", en:"Drawer", ph:"Ga-ve-ta"},
            {pt:"Geladeira", en:"Refrigerator", ph:"Zhe-la-dey-ra"}, {pt:"Fogão", en:"Stove", ph:"Fo-gowm"},
            {pt:"Microondas", en:"Microwave", ph:"Mee-cro-on-das"}, {pt:"Chuveiro", en:"Shower", ph:"Shoo-vey-ro"},
            {pt:"Banheiro", en:"Bathroom", ph:"Ban-yey-ro"}, {pt:"Quintal", en:"Backyard", ph:"Keen-tal"},
            {pt:"Varanda", en:"Balcony/Porch", ph:"Va-ran-da"}, {pt:"Escada", en:"Stairs", ph:"Es-ca-da"},
            {pt:"Teto", en:"Ceiling", ph:"Te-to"}, {pt:"Parede", en:"Wall", ph:"Pa-re-jee"},
            {pt:"Chão", en:"Floor/Ground", ph:"Showm"},
            // Nouns — City & Transport
            {pt:"Ônibus", en:"Bus", ph:"Oh-nee-boos"}, {pt:"Metrô", en:"Subway/Metro", ph:"Me-troh"},
            {pt:"Trem", en:"Train", ph:"Trem"}, {pt:"Avião", en:"Airplane", ph:"A-vya-owm"},
            {pt:"Táxi", en:"Taxi", ph:"Tax-ee"}, {pt:"Moto", en:"Motorcycle", ph:"Mo-to"},
            {pt:"Bairro", en:"Neighborhood", ph:"Bye-ho"}, {pt:"Praça", en:"Square/Plaza", ph:"Pra-sa"},
            {pt:"Esquina", en:"Street corner", ph:"Es-kee-na"}, {pt:"Semáforo", en:"Traffic light", ph:"Se-ma-fo-ro"},
            {pt:"Calçada", en:"Sidewalk", ph:"Cal-sa-da"}, {pt:"Ponte", en:"Bridge", ph:"Pon-chee"},
            // Adjectives
            {pt:"Cansado", en:"Tired", ph:"Can-sa-do"}, {pt:"Ocupado", en:"Busy", ph:"O-coo-pa-do"},
            {pt:"Livre", en:"Free", ph:"Lee-vree"}, {pt:"Cheio", en:"Full", ph:"Shey-o"},
            {pt:"Vazio", en:"Empty", ph:"Va-zyo"}, {pt:"Pesado", en:"Heavy", ph:"Pe-za-do"},
            {pt:"Leve", en:"Light (weight)", ph:"Le-vee"}, {pt:"Largo", en:"Wide", ph:"Lar-go"},
            {pt:"Estreito", en:"Narrow", ph:"Es-trey-to"}, {pt:"Alto", en:"Tall/High", ph:"Al-to"},
            {pt:"Baixo", en:"Short/Low", ph:"Bye-sho"}, {pt:"Gordo", en:"Fat", ph:"Gor-do"},
            {pt:"Magro", en:"Thin/Slim", ph:"Ma-gro"}, {pt:"Forte", en:"Strong", ph:"For-chee"},
            {pt:"Fraco", en:"Weak", ph:"Fra-co"}, {pt:"Rico", en:"Rich", ph:"Hee-co"},
            {pt:"Pobre", en:"Poor", ph:"Po-bree"}, {pt:"Sozinho", en:"Alone", ph:"So-zeen-yo"},
            {pt:"Juntos", en:"Together", ph:"Zhoon-tos"}, {pt:"Diferente", en:"Different", ph:"Jee-fe-ren-chee"},
            {pt:"Igual", en:"Equal/Same", ph:"Ee-gwal"}, {pt:"Seguro", en:"Safe/Secure", ph:"Se-goo-ro"},
            {pt:"Perigoso", en:"Dangerous", ph:"Pe-ree-go-zo"}, {pt:"Famoso", en:"Famous", ph:"Fa-mo-zo"},
            {pt:"Estranho", en:"Strange", ph:"Es-tran-yo"}, {pt:"Estressado", en:"Stressed", ph:"Es-tres-sa-do"},
            // Food & Meals
            {pt:"Almoço", en:"Lunch", ph:"Al-mo-so"}, {pt:"Jantar", en:"Dinner", ph:"Zhan-tar"},
            {pt:"Café da manhã", en:"Breakfast", ph:"Ca-feh da ma-nyah"}, {pt:"Sobremesa", en:"Dessert", ph:"So-bre-me-za"},
            {pt:"Sopa", en:"Soup", ph:"So-pa"}, {pt:"Salada", en:"Salad", ph:"Sa-la-da"},
            {pt:"Macarrão", en:"Pasta/Noodles", ph:"Ma-ca-howm"}, {pt:"Bolo", en:"Cake", ph:"Bo-lo"},
            {pt:"Biscoito", en:"Cookie/Biscuit", ph:"Bees-coy-to"}, {pt:"Sorvete", en:"Ice cream", ph:"Sor-ve-chee"},
            {pt:"Manteiga", en:"Butter", ph:"Man-tey-ga"}, {pt:"Azeite", en:"Olive oil", ph:"A-zey-chee"},
            {pt:"Vinagre", en:"Vinegar", ph:"Vee-na-gree"}, {pt:"Pimenta", en:"Pepper", ph:"Pee-men-ta"},
            {pt:"Alho", en:"Garlic", ph:"Al-yo"}, {pt:"Cebola", en:"Onion", ph:"Se-bo-la"},
            {pt:"Tomate", en:"Tomato", ph:"To-ma-chee"}, {pt:"Batata", en:"Potato", ph:"Ba-ta-ta"},
            {pt:"Cenoura", en:"Carrot", ph:"Se-no-ra"}, {pt:"Alface", en:"Lettuce", ph:"Al-fa-see"},
            // Time & Calendar
            {pt:"Ontem", en:"Yesterday", ph:"On-tem"}, {pt:"Hoje", en:"Today", ph:"O-zhee"},
            {pt:"Semana", en:"Week", ph:"Se-ma-na"}, {pt:"Mês", en:"Month", ph:"Mesh"},
            {pt:"Ano", en:"Year", ph:"An-o"}, {pt:"Hora", en:"Hour", ph:"O-ra"},
            {pt:"Minuto", en:"Minute", ph:"Mee-noo-to"}, {pt:"Segundo", en:"Second", ph:"Se-goon-do"},
            {pt:"Segunda-feira", en:"Monday", ph:"Se-goon-da fey-ra"}, {pt:"Terça-feira", en:"Tuesday", ph:"Ter-sa fey-ra"},
            {pt:"Quarta-feira", en:"Wednesday", ph:"Kwar-ta fey-ra"}, {pt:"Quinta-feira", en:"Thursday", ph:"Keen-ta fey-ra"},
            {pt:"Sexta-feira", en:"Friday", ph:"Ses-ta fey-ra"}, {pt:"Sábado", en:"Saturday", ph:"Sa-ba-do"},
            {pt:"Domingo", en:"Sunday", ph:"Do-meen-go"},
            // Emotions & States
            {pt:"Saudade", en:"Nostalgic longing", ph:"Sow-da-jee"}, {pt:"Raiva", en:"Anger", ph:"Hy-va"},
            {pt:"Medo", en:"Fear", ph:"Me-do"}, {pt:"Alegria", en:"Joy", ph:"A-le-gree-a"},
            {pt:"Tristeza", en:"Sadness", ph:"Trees-te-za"}, {pt:"Surpresa", en:"Surprise", ph:"Sur-pre-za"},
            {pt:"Vergonha", en:"Shame/Embarrassment", ph:"Ver-gon-ya"}, {pt:"Orgulho", en:"Pride", ph:"Or-goo-lyo"},
            {pt:"Ciúme", en:"Jealousy", ph:"Syoo-mee"}, {pt:"Inveja", en:"Envy", ph:"Een-ve-zha"},
            {pt:"Ansiedade", en:"Anxiety", ph:"An-sye-da-jee"}, {pt:"Calma", en:"Calm", ph:"Cal-ma"},
            // Health
            {pt:"Médico", en:"Doctor", ph:"Me-jee-co"}, {pt:"Remédio", en:"Medicine", ph:"He-me-jyo"},
            {pt:"Dor", en:"Pain", ph:"Dor"}, {pt:"Febre", en:"Fever", ph:"Fe-bree"},
            {pt:"Tosse", en:"Cough", ph:"To-see"}, {pt:"Resfriado", en:"Cold (illness)", ph:"Hes-free-a-do"},
            {pt:"Cansaço", en:"Fatigue", ph:"Can-sa-so"}, {pt:"Saúde", en:"Health", ph:"Sa-oo-jee"},
        ],
        hard: [
            // Original entries
            {pt:"Borboleta", en:"Butterfly", ph:"Bor-bo-le-ta"}, {pt:"Esquilo", en:"Squirrel", ph:"Es-kee-lo"},
            {pt:"Empreendimento", en:"Venture", ph:"Em-pree-en-jee-men-to"}, {pt:"Responsabilidade", en:"Responsibility", ph:"Res-pon-sa-bee-lee-da-jee"},
            {pt:"Conhecimento", en:"Knowledge", ph:"Co-nye-see-men-to"}, {pt:"Desenvolvimento", en:"Development", ph:"De-zen-vol-vee-men-to"},
            {pt:"Questionamento", en:"Questioning", ph:"Kes-tyo-na-men-to"}, {pt:"Extraordinário", en:"Extraordinary", ph:"Es-tra-or-jee-na-ryo"},
            {pt:"Significado", en:"Meaning", ph:"Seeg-nee-fee-ca-do"}, {pt:"Liberdade", en:"Freedom", ph:"Lee-ber-da-jee"},
            {pt:"Sociedade", en:"Society", ph:"So-sye-da-jee"}, {pt:"Sentimento", en:"Feeling", ph:"Sen-chee-men-to"},
            // NEW hard words — Abstract nouns
            {pt:"Consciência", en:"Conscience/Awareness", ph:"Con-syen-sya"}, {pt:"Comportamento", en:"Behaviour", ph:"Com-por-ta-men-to"},
            {pt:"Estabelecimento", en:"Establishment", ph:"Es-ta-be-le-see-men-to"}, {pt:"Acontecimento", en:"Event/Occurrence", ph:"A-con-te-see-men-to"},
            {pt:"Circunstância", en:"Circumstance", ph:"Seer-coon-stan-sya"}, {pt:"Consequência", en:"Consequence", ph:"Con-se-kwen-sya"},
            {pt:"Experiência", en:"Experience", ph:"Es-pe-ryen-sya"}, {pt:"Influência", en:"Influence", ph:"Een-flwen-sya"},
            {pt:"Referência", en:"Reference", ph:"He-fe-ren-sya"}, {pt:"Independência", en:"Independence", ph:"Een-de-pen-den-sya"},
            {pt:"Transparência", en:"Transparency", ph:"Trans-pa-ren-sya"}, {pt:"Persistência", en:"Persistence", ph:"Per-sees-ten-sya"},
            {pt:"Competência", en:"Competence", ph:"Com-pe-ten-sya"}, {pt:"Conveniência", en:"Convenience", ph:"Con-ve-nyen-sya"},
            {pt:"Curiosidade", en:"Curiosity", ph:"Coo-ryo-zee-da-jee"}, {pt:"Dificuldade", en:"Difficulty", ph:"Jee-fee-cool-da-jee"},
            {pt:"Oportunidade", en:"Opportunity", ph:"O-por-too-nee-da-jee"}, {pt:"Necessidade", en:"Necessity", ph:"Ne-se-see-da-jee"},
            {pt:"Possibilidade", en:"Possibility", ph:"Po-see-bee-lee-da-jee"}, {pt:"Realidade", en:"Reality", ph:"He-a-lee-da-jee"},
            {pt:"Personalidade", en:"Personality", ph:"Per-so-na-lee-da-jee"}, {pt:"Identidade", en:"Identity", ph:"Ee-den-chee-da-jee"},
            {pt:"Complexidade", en:"Complexity", ph:"Com-ple-see-da-jee"}, {pt:"Humanidade", en:"Humanity", ph:"Oo-ma-nee-da-jee"},
            {pt:"Generosidade", en:"Generosity", ph:"Zhe-ne-ro-zee-da-jee"}, {pt:"Criatividade", en:"Creativity", ph:"Cree-a-chee-vee-da-jee"},
            {pt:"Solidariedade", en:"Solidarity", ph:"So-lee-da-rye-da-jee"}, {pt:"Sustentabilidade", en:"Sustainability", ph:"Soos-ten-ta-bee-lee-da-jee"},
            {pt:"Reconhecimento", en:"Recognition", ph:"He-con-ye-see-men-to"}, {pt:"Aperfeiçoamento", en:"Improvement/Perfection", ph:"A-per-fey-swa-men-to"},
            // Complex verbs
            {pt:"Comprometer", en:"To commit/compromise", ph:"Com-pro-me-tehr"}, {pt:"Estabelecer", en:"To establish", ph:"Es-ta-be-le-sehr"},
            {pt:"Desenvolver", en:"To develop", ph:"De-zen-vol-vehr"}, {pt:"Manifestar", en:"To manifest", ph:"Ma-nee-fes-tar"},
            {pt:"Implementar", en:"To implement", ph:"Eem-ple-men-tar"}, {pt:"Administrar", en:"To manage/administer", ph:"Ad-mee-nees-trar"},
            {pt:"Comunicar", en:"To communicate", ph:"Co-moo-nee-car"}, {pt:"Demonstrar", en:"To demonstrate", ph:"De-mon-strar"},
            {pt:"Representar", en:"To represent", ph:"He-pre-zen-tar"}, {pt:"Interpretar", en:"To interpret", ph:"Een-ter-pre-tar"},
            {pt:"Transformar", en:"To transform", ph:"Trans-for-mar"}, {pt:"Conquistar", en:"To conquer/achieve", ph:"Con-kees-tar"},
            {pt:"Abandonar", en:"To abandon", ph:"A-ban-do-nar"}, {pt:"Superar", en:"To overcome", ph:"Soo-pe-rar"},
            {pt:"Imaginar", en:"To imagine", ph:"Ee-ma-zhee-nar"}, {pt:"Contribuir", en:"To contribute", ph:"Con-tree-boo-eer"},
            {pt:"Recomendar", en:"To recommend", ph:"He-co-men-dar"}, {pt:"Considerar", en:"To consider", ph:"Con-see-de-rar"},
            {pt:"Compreender", en:"To understand (fully)", ph:"Com-pre-en-dehr"}, {pt:"Surpreender", en:"To surprise", ph:"Sur-pre-en-dehr"},
            // Complex adjectives
            {pt:"Impressionante", en:"Impressive", ph:"Eem-pres-syo-nan-chee"}, {pt:"Desafiador", en:"Challenging", ph:"De-za-fya-dor"},
            {pt:"Inconveniente", en:"Inconvenient", ph:"Een-con-ve-nyen-chee"}, {pt:"Surpreendente", en:"Surprising", ph:"Sur-pree-en-den-chee"},
            {pt:"Preocupante", en:"Worrying", ph:"Pre-o-coo-pan-chee"}, {pt:"Reconhecível", en:"Recognisable", ph:"He-con-ye-see-vel"},
            {pt:"Inacreditável", en:"Unbelievable", ph:"Een-a-cre-jee-ta-vel"}, {pt:"Indispensável", en:"Indispensable", ph:"Een-jees-pen-sa-vel"},
            {pt:"Invulnerável", en:"Invulnerable", ph:"Een-vool-ne-ra-vel"}, {pt:"Irresponsável", en:"Irresponsible", ph:"Ee-hes-pon-sa-vel"},
            {pt:"Incompreensível", en:"Incomprehensible", ph:"Een-com-pre-en-see-vel"}, {pt:"Interminável", en:"Endless", ph:"Een-ter-mee-na-vel"},
        ],
        vhard: [
            // Original entries
            {pt:"Paralelepípedo", en:"Cobblestone", ph:"Pa-ra-le-le-pee-pe-do"},
            {pt:"Inconstitucional", en:"Unconstitutional", ph:"In-cons-tee-too-shon-al"},
            {pt:"Otorrinolaringologista", en:"ENT Doctor", ph:"O-to-hee-no-la-reen-go-lo-zhees-ta"},
            {pt:"Desoxirribonucleico", en:"DNA (adj.)", ph:"De-zo-shee-hee-bo-noo-cle-ee-co"},
            {pt:"Saudade", en:"Nostalgic Longing", ph:"Sow-da-jee"},
            {pt:"Anticonstitucionalissimamente", en:"Very unconstitutionally", ph:"An-tee-cons-tee-too-syo-na-lees-see-ma-men-chee"},
            {pt:"Pneumoultramicroscopicosiliconovolcanoconiose", en:"Lung disease", ph:"Pneu-mo-ool-tra-mee-cros-co-pee-co-see-lee-co-no-vol-ca-no-co-nyo-ze"},
            {pt:"Deslumbrante", en:"Stunning", ph:"De-zlum-bran-chee"},
            // NEW vhard words
            {pt:"Reinterpretação", en:"Reinterpretation", ph:"He-een-ter-pre-ta-sowm"}, {pt:"Reestruturação", en:"Restructuring", ph:"He-es-troo-too-ra-sowm"},
            {pt:"Constitucionalidade", en:"Constitutionality", ph:"Con-stee-too-syo-na-lee-da-jee"}, {pt:"Internacionalização", en:"Internationalisation", ph:"Een-ter-na-syo-na-lee-za-sowm"},
            {pt:"Telecomunicações", en:"Telecommunications", ph:"Te-le-co-moo-nee-ca-soysh"}, {pt:"Desindustrialização", en:"Deindustrialisation", ph:"De-zeen-doos-tree-a-lee-za-sowm"},
            {pt:"Irresponsabilidade", en:"Irresponsibility", ph:"Ee-hes-pon-sa-bee-lee-da-jee"}, {pt:"Incompatibilidade", en:"Incompatibility", ph:"Een-com-pa-chee-bee-lee-da-jee"},
            {pt:"Descontextualização", en:"Decontextualisation", ph:"Des-con-tex-too-a-lee-za-sowm"}, {pt:"Imprevisibilidade", en:"Unpredictability", ph:"Eem-pre-vee-zee-bee-lee-da-jee"},
            {pt:"Corresponsabilidade", en:"Co-responsibility", ph:"Co-hes-pon-sa-bee-lee-da-jee"}, {pt:"Indiscriminadamente", en:"Indiscriminately", ph:"Een-jees-cree-mee-na-da-men-chee"},
            {pt:"Institucionalização", en:"Institutionalisation", ph:"Ees-tee-too-syo-na-lee-za-sowm"}, {pt:"Contraproducentemente", en:"Counterproductively", ph:"Con-tra-pro-doo-sen-te-men-chee"},
            {pt:"Desconsideração", en:"Disregard", ph:"Des-con-see-de-ra-sowm"}, {pt:"Incomensurável", en:"Immeasurable", ph:"Een-co-men-soo-ra-vel"},
            {pt:"Transdisciplinaridade", en:"Transdisciplinarity", ph:"Trans-jees-see-plee-na-ree-da-jee"}, {pt:"Autoconhecimento", en:"Self-knowledge", ph:"Ow-to-co-nye-see-men-to"},
            {pt:"Multiculturalismo", en:"Multiculturalism", ph:"Mool-chee-cool-too-ra-leez-mo"}, {pt:"Contemporaneidade", en:"Contemporaneity", ph:"Con-tem-po-ra-ne-ee-da-jee"},
        ]
    },
    phrases: {
        easy: [
            // Original entries
            {pt:"Como você está?", en:"How are you?", ph:"Co-mo vo-say es-ta"},
            {pt:"Qual o seu nome?", en:"What is your name?", ph:"Kwal o seu no-mee"},
            // NEW easy phrases — Greetings & Basics
            {pt:"Olá!", en:"Hello!", ph:"O-la"}, {pt:"Oi!", en:"Hi!", ph:"Oy"},
            {pt:"Bom dia!", en:"Good morning!", ph:"Bom jee-a"}, {pt:"Boa tarde!", en:"Good afternoon!", ph:"Bo-a tar-jee"},
            {pt:"Boa noite!", en:"Good night/evening!", ph:"Bo-a noy-chee"}, {pt:"Tchau!", en:"Bye!", ph:"Chow"},
            {pt:"Até logo!", en:"See you later!", ph:"A-teh lo-go"}, {pt:"Até amanhã!", en:"See you tomorrow!", ph:"A-teh a-ma-nyah"},
            {pt:"Por favor.", en:"Please.", ph:"Por fa-vor"}, {pt:"Obrigado/a.", en:"Thank you.", ph:"O-bree-ga-do/da"},
            {pt:"De nada.", en:"You're welcome.", ph:"Jee na-da"}, {pt:"Com licença.", en:"Excuse me.", ph:"Com lee-sen-sa"},
            {pt:"Desculpe.", en:"Sorry.", ph:"Des-cool-pee"}, {pt:"Tudo bem?", en:"Everything okay?", ph:"Too-do bem"},
            {pt:"Tudo bem!", en:"Everything's fine!", ph:"Too-do bem"}, {pt:"Sim.", en:"Yes.", ph:"Seeng"},
            {pt:"Não.", en:"No.", ph:"Nowm"}, {pt:"Talvez.", en:"Maybe.", ph:"Tal-vez"},
            {pt:"Eu não sei.", en:"I don't know.", ph:"Ew nowm say"}, {pt:"Eu entendo.", en:"I understand.", ph:"Ew en-ten-do"},
            {pt:"Eu não entendo.", en:"I don't understand.", ph:"Ew nowm en-ten-do"}, {pt:"Pode repetir?", en:"Can you repeat?", ph:"Po-jee he-pe-cheer"},
            {pt:"Fala mais devagar.", en:"Speak more slowly.", ph:"Fa-la mice de-va-gar"}, {pt:"Onde fica o banheiro?", en:"Where is the bathroom?", ph:"On-jee fee-ca o ban-yey-ro"},
            {pt:"Quanto custa?", en:"How much does it cost?", ph:"Kwan-to coos-ta"}, {pt:"Eu gostaria de...", en:"I would like...", ph:"Ew gos-ta-ree-a jee"},
            {pt:"Que horas são?", en:"What time is it?", ph:"Ke o-ras sowm"}, {pt:"Qual é o seu telefone?", en:"What is your phone number?", ph:"Kwal eh o seu te-le-fo-nee"},
            {pt:"Eu me chamo...", en:"My name is...", ph:"Ew mee sha-mo"}, {pt:"Prazer em conhecê-lo!", en:"Nice to meet you!", ph:"Pra-zehr em co-nye-seh-lo"},
            {pt:"Feliz aniversário!", en:"Happy birthday!", ph:"Fe-leez a-nee-ver-sa-ryo"}, {pt:"Feliz Natal!", en:"Merry Christmas!", ph:"Fe-leez na-tal"},
            {pt:"Boa sorte!", en:"Good luck!", ph:"Bo-a sor-chee"}, {pt:"Parabéns!", en:"Congratulations!", ph:"Pa-ra-benzh"},
            {pt:"Com certeza!", en:"Of course!/Certainly!", ph:"Com ser-te-za"}, {pt:"Claro!", en:"Sure!/Of course!", ph:"Cla-ro"},
            {pt:"Que saudade!", en:"I missed you/How I miss it!", ph:"Ke sow-da-jee"}, {pt:"Tô com fome.", en:"I'm hungry.", ph:"Toh com fo-mee"},
            {pt:"Tô com sede.", en:"I'm thirsty.", ph:"Toh com se-jee"}, {pt:"Tô com sono.", en:"I'm sleepy.", ph:"Toh com so-no"},
            {pt:"Me ajuda?", en:"Can you help me?", ph:"Mee a-zhoo-da"}, {pt:"Qual é o seu e-mail?", en:"What is your email?", ph:"Kwal eh o seu ee-mayl"},
            // More easy phrases — Daily life
            {pt:"Que horas são?", en:"What time is it?", ph:"Ke o-ras sowm"}, {pt:"Que dia é hoje?", en:"What day is it today?", ph:"Ke jee-a eh o-zhee"},
            {pt:"Tudo bem com você?", en:"Are you okay?", ph:"Too-do bem com vo-say"}, {pt:"Faz favor!", en:"Excuse me! (getting attention)", ph:"Faz fa-vor"},
            {pt:"Que pena!", en:"What a shame!", ph:"Ke pe-na"}, {pt:"Que legal!", en:"How cool!", ph:"Ke le-gal"},
            {pt:"Que saudade de você!", en:"I really miss you!", ph:"Ke sow-da-jee jee vo-say"}, {pt:"Fique à vontade!", en:"Make yourself at home!", ph:"Fee-kee ah von-ta-jee"},
            {pt:"Vamos lá!", en:"Let's go!", ph:"Va-mos la"}, {pt:"Pode deixar!", en:"No worries!/Leave it to me!", ph:"Po-jee dey-shar"},
            {pt:"Que bonito/a!", en:"How beautiful!", ph:"Ke bo-nee-to/ta"}, {pt:"Que delícia!", en:"How delicious!", ph:"Ke de-lee-sya"},
            {pt:"Tô bem, obrigado/a.", en:"I'm well, thanks.", ph:"Toh bem o-bree-ga-do/da"}, {pt:"Boa viagem!", en:"Have a good trip!", ph:"Bo-a vya-zhem"},
        ],
        medium: [
            {pt:"Eu moro no Brasil há dois anos.", en:"I have lived in Brazil for two years.", ph:"Ew mo-ro no bra-zeel ah doys an-os"},
            {pt:"Você pode me ajudar, por favor?", en:"Can you help me, please?", ph:"Vo-say po-jee mee a-zhoo-dar por fa-vor"},
            {pt:"Qual é o melhor restaurante perto daqui?", en:"What is the best restaurant nearby?", ph:"Kwal eh o me-lyor hes-tow-ran-chee per-to da-kee"},
            {pt:"Eu estou aprendendo português.", en:"I am learning Portuguese.", ph:"Ew es-toh a-pren-den-do por-too-gesh"},
            {pt:"Não é bem assim.", en:"That's not quite right.", ph:"Nowm eh bem a-seem"},
            {pt:"Isso depende da situação.", en:"That depends on the situation.", ph:"Ee-so de-pen-jee da see-too-a-sowm"},
            {pt:"Posso te ligar mais tarde?", en:"Can I call you later?", ph:"Po-so chee lee-gar mice tar-jee"},
            {pt:"O que você acha disso?", en:"What do you think about this?", ph:"O ke vo-say a-sha jee-so"},
            {pt:"Preciso de uma hora para terminar.", en:"I need an hour to finish.", ph:"Pre-see-zo jee oo-ma o-ra pa-ra ter-mee-nar"},
            {pt:"Você já visitou o Rio de Janeiro?", en:"Have you ever visited Rio de Janeiro?", ph:"Vo-say zha vee-zee-toh o hee-o jee zha-ney-ro"},
            {pt:"Vamos marcar para a semana que vem?", en:"Shall we schedule for next week?", ph:"Va-mos mar-car pa-ra a se-ma-na ke vem"},
            {pt:"Eu prefiro ficar em casa hoje.", en:"I prefer to stay home today.", ph:"Ew pre-fee-ro fee-car em ca-za o-zhee"},
            {pt:"Você fala algum outro idioma?", en:"Do you speak any other language?", ph:"Vo-say fa-la al-goom oo-tro ee-dyo-ma"},
            {pt:"Isso é muito importante para mim.", en:"This is very important to me.", ph:"Ee-so eh mwee-to eem-por-tan-chee pa-ra meem"},
            {pt:"Que tipo de música você gosta?", en:"What kind of music do you like?", ph:"Ke chee-po jee moo-zee-ca vo-say gos-ta"},
            {pt:"Estou com dor de cabeça.", en:"I have a headache.", ph:"Es-toh com dor jee ca-be-sa"},
            {pt:"Quanto tempo leva para chegar?", en:"How long does it take to get there?", ph:"Kwan-to tem-po le-va pa-ra she-gar"},
            {pt:"Pode me dar uma dica?", en:"Can you give me a tip/hint?", ph:"Po-jee mee dar oo-ma jee-ca"},
            {pt:"Eu estava pensando em você.", en:"I was thinking about you.", ph:"Ew es-ta-va pen-san-do em vo-say"},
            {pt:"Isso me faz muito feliz.", en:"This makes me very happy.", ph:"Ee-so mee faz mwee-to fe-leez"},
            {pt:"Você quer tomar alguma coisa?", en:"Would you like something to drink?", ph:"Vo-say ker to-mar al-goo-ma coy-za"},
            {pt:"Eu não consigo dormir.", en:"I can't sleep.", ph:"Ew nowm con-see-go dor-meer"},
            {pt:"A conta, por favor.", en:"The bill, please.", ph:"A con-ta por fa-vor"},
            {pt:"Tem algum problema?", en:"Is there any problem?", ph:"Tem al-goom pro-ble-ma"},
            {pt:"Eu vou pensar nisso.", en:"I will think about it.", ph:"Ew voh pen-sar nee-so"},
            {pt:"Com quem você mora?", en:"Who do you live with?", ph:"Com kem vo-say mo-ra"},
            {pt:"Que dia é hoje?", en:"What day is today?", ph:"Ke jee-a eh o-zhee"},
            {pt:"O ônibus passa às nove.", en:"The bus comes at nine.", ph:"O oh-nee-boos pa-sa ash no-vee"},
            {pt:"Você já comeu hoje?", en:"Have you eaten today?", ph:"Vo-say zha co-mew o-zhee"},
            {pt:"Eu não me lembro disso.", en:"I don't remember that.", ph:"Ew nowm mee lem-bro jee-so"},
            // More medium phrases
            {pt:"Onde você trabalha?", en:"Where do you work?", ph:"On-jee vo-say tra-ba-lya"},
            {pt:"Há quanto tempo você estuda português?", en:"How long have you been studying Portuguese?", ph:"Ah kwan-to tem-po vo-say es-too-da por-too-gesh"},
            {pt:"Eu gosto muito de música brasileira.", en:"I really like Brazilian music.", ph:"Ew gos-to mwee-to jee moo-zee-ca bra-zee-ley-ra"},
            {pt:"Você pode me mostrar no mapa?", en:"Can you show me on the map?", ph:"Vo-say po-jee mee mos-trar no ma-pa"},
            {pt:"Tem alguma coisa vegetariana?", en:"Is there anything vegetarian?", ph:"Tem al-goo-ma coy-za ve-zhe-ta-rya-na"},
            {pt:"Eu preciso trocar dinheiro.", en:"I need to exchange money.", ph:"Ew pre-see-zo tro-car jee-nyey-ro"},
            {pt:"Posso usar o seu carregador?", en:"Can I use your charger?", ph:"Po-so oo-zar o seu ca-he-ga-dor"},
            {pt:"Você tem recomendações de passeios?", en:"Do you have any sightseeing recommendations?", ph:"Vo-say tem he-co-men-da-soyns jee pa-sey-os"},
            {pt:"Que saudades do Brasil!", en:"I really miss Brazil!", ph:"Ke sow-da-jees do bra-zeel"},
            {pt:"Você consegue me dar um desconto?", en:"Can you give me a discount?", ph:"Vo-say con-se-gee mee dar oom des-con-to"},
        ],
        hard: [
            {pt:"Espero que tudo se resolva da melhor forma possível.", en:"I hope everything works out in the best way possible.", ph:"Es-pe-ro ke too-do se he-sol-va da me-lyor for-ma po-see-vel"},
            {pt:"Você poderia me explicar como funciona?", en:"Could you explain to me how it works?", ph:"Vo-say po-de-ree-a mee es-plee-car co-mo foon-syo-na"},
            {pt:"Não vale a pena se preocupar com isso agora.", en:"It's not worth worrying about that now.", ph:"Nowm va-lee a pe-na se pre-o-coo-par com ee-so a-go-ra"},
            {pt:"Tenho muito a aprender com essa experiência.", en:"I have a lot to learn from this experience.", ph:"Ten-yo mwee-to a a-pren-dehr com es-sa es-pe-ryen-sya"},
            {pt:"Quanto mais pratico, mais aprendo.", en:"The more I practise, the more I learn.", ph:"Kwan-to mice pra-chee-co mice a-pren-do"},
            {pt:"Por mais que eu tente, não consigo parar de pensar.", en:"No matter how hard I try, I can't stop thinking.", ph:"Por mice ke ew ten-chee nowm con-see-go pa-rar jee pen-sar"},
            {pt:"A vida é muito mais do que aquilo que vemos.", en:"Life is much more than what we see.", ph:"A vee-da eh mwee-to mice do ke a-kee-lo ke ve-mos"},
            {pt:"Cada pessoa tem uma perspectiva diferente.", en:"Every person has a different perspective.", ph:"Ca-da pe-so-a tem oo-ma pers-pec-chee-va jee-fe-ren-chee"},
            {pt:"Demorou, mas finalmente chegamos a um acordo.", en:"It took a while, but we finally reached an agreement.", ph:"De-mo-row mas fee-nal-men-chee she-ga-mos a oom a-cor-do"},
            {pt:"Você consegue imaginar como seria sem tecnologia?", en:"Can you imagine what it would be like without technology?", ph:"Vo-say con-se-gee ee-ma-zhee-nar co-mo se-ree-a sem tec-no-lo-zhya"},
            {pt:"É preciso ter paciência para aprender um idioma.", en:"You need to have patience to learn a language.", ph:"Eh pre-see-zo tehr pa-syen-sya pa-ra a-pren-dehr oom ee-dyo-ma"},
            {pt:"Sem comunicação não há relacionamento.", en:"Without communication there is no relationship.", ph:"Sem co-moo-nee-ca-sowm nowm ah he-la-syo-na-men-to"},
            // More hard phrases
            {pt:"Não consigo acreditar como o tempo passa rápido.", en:"I can't believe how fast time flies.", ph:"Nowm con-see-go a-cre-jee-tar co-mo o tem-po pa-sa ha-pee-do"},
            {pt:"Gostaria de saber mais sobre a cultura brasileira.", en:"I would like to know more about Brazilian culture.", ph:"Gos-ta-ree-a jee sa-behr mice so-bree a cool-too-ra bra-zee-ley-ra"},
            {pt:"Não é bem o que eu queria dizer.", en:"That's not quite what I meant.", ph:"Nowm eh bem o ke ew ke-ree-a jee-zehr"},
            {pt:"É mais fácil falar do que fazer.", en:"It's easier said than done.", ph:"Eh mice fa-seel fa-lar do ke fa-zehr"},
            {pt:"Você tem alguma sugestão de onde eu possa aprender mais?", en:"Do you have any suggestion of where I can learn more?", ph:"Vo-say tem al-goo-ma soo-zhes-towm jee on-jee ew po-sa a-pren-dehr mice"},
            {pt:"Às vezes o silêncio diz mais do que as palavras.", en:"Sometimes silence says more than words.", ph:"Ash ve-zes o see-len-syo jiz mice do ke as pa-la-vras"},
        ],
        vhard: [
            // Original entries
            {pt:"Enfiar o pé na jaca", en:"To overindulge", ph:"Idiom"},
            {pt:"Dar murro em ponta de faca", en:"To beat a dead horse", ph:"Idiom"},
            // NEW vhard phrases — Idioms & Complex expressions
            {pt:"Chutar o balde", en:"To give up/lose it (lit: to kick the bucket)", ph:"Idiom"},
            {pt:"Estar com a pulga atrás da orelha", en:"To be suspicious (lit: to have a flea behind the ear)", ph:"Idiom"},
            {pt:"Não é pra qualquer um", en:"It's not for everyone", ph:"Nowm eh pra kwal-ker oom"},
            {pt:"Fazer vista grossa", en:"To turn a blind eye", ph:"Idiom"},
            {pt:"Pisar em ovos", en:"To tread carefully (lit: to step on eggs)", ph:"Idiom"},
            {pt:"Estar com dois pés esquerdos", en:"To be clumsy (lit: to have two left feet)", ph:"Idiom"},
            {pt:"Pôr a mão na massa", en:"To get to work/roll up sleeves", ph:"Idiom"},
            {pt:"Quem não tem cão caça com gato", en:"Use what you have (lit: who has no dog hunts with a cat)", ph:"Idiom"},
            {pt:"Água mole em pedra dura tanto bate até que fura", en:"Constant effort overcomes any obstacle", ph:"Proverb"},
            {pt:"Cada macaco no seu galho", en:"Mind your own business (lit: each monkey on its own branch)", ph:"Idiom"},
            {pt:"Em terra de cego quem tem um olho é rei", en:"In the land of the blind the one-eyed man is king", ph:"Proverb"},
            {pt:"Não existe almoço grátis", en:"There's no such thing as a free lunch", ph:"No-w... ah... ees-to al-mo-so gra-chees"},
            {pt:"Quem com ferro fere com ferro será ferido", en:"He who lives by the sword dies by the sword", ph:"Proverb"},
            {pt:"A ocasião faz o ladrão", en:"Opportunity makes the thief", ph:"A o-ca-zyowm faz o la-drowm"},
            {pt:"Devagar se vai ao longe", en:"Slow and steady wins the race", ph:"De-va-gar see vye aw lon-zhee"},
            {pt:"Não adianta chorar o leite derramado", en:"No use crying over spilt milk", ph:"Proverb"},
        ]
    }
};