const SPANISH_LIBRARY = {
    words: {
        easy: [
            // Original entries
            {sp:"Hola", en:"Hello", ph:"O-la"}, {sp:"Gracias", en:"Thank you", ph:"Gra-syas"},
            {sp:"Agua", en:"Water", ph:"Ah-gwa"}, {sp:"Sol", en:"Sun", ph:"Sol"},
            {sp:"Luna", en:"Moon", ph:"Loo-na"}, {sp:"Perro", en:"Dog", ph:"Pe-rro"},
            {sp:"Gato", en:"Cat", ph:"Ga-to"}, {sp:"Casa", en:"House", ph:"Ca-sa"},
            {sp:"Libro", en:"Book", ph:"Lee-bro"}, {sp:"Amigo", en:"Friend", ph:"A-mee-go"},
            {sp:"Comida", en:"Food", ph:"Co-mee-da"}, {sp:"Leche", en:"Milk", ph:"Le-che"},
            {sp:"Mesa", en:"Table", ph:"Me-sa"}, {sp:"Flor", en:"Flower", ph:"Flor"},
            {sp:"Calle", en:"Street", ph:"Ka-ye"},
            // NEW easy — Body parts
            {sp:"Cabeza", en:"Head", ph:"Ca-be-sa"}, {sp:"Ojo", en:"Eye", ph:"O-ho"},
            {sp:"Nariz", en:"Nose", ph:"Na-rees"}, {sp:"Boca", en:"Mouth", ph:"Bo-ca"},
            {sp:"Oreja", en:"Ear", ph:"O-re-ha"}, {sp:"Mano", en:"Hand", ph:"Ma-no"},
            {sp:"Pie", en:"Foot", ph:"Pye"}, {sp:"Brazo", en:"Arm", ph:"Bra-so"},
            {sp:"Pierna", en:"Leg", ph:"Pyer-na"}, {sp:"Dedo", en:"Finger/Toe", ph:"De-do"},
            {sp:"Espalda", en:"Back", ph:"Es-pal-da"}, {sp:"Cuello", en:"Neck", ph:"Kwe-yo"},
            {sp:"Pelo", en:"Hair", ph:"Pe-lo"}, {sp:"Cara", en:"Face", ph:"Ca-ra"},
            // Colors
            {sp:"Rojo", en:"Red", ph:"Ro-ho"}, {sp:"Azul", en:"Blue", ph:"A-sool"},
            {sp:"Verde", en:"Green", ph:"Ber-de"}, {sp:"Amarillo", en:"Yellow", ph:"A-ma-ree-yo"},
            {sp:"Blanco", en:"White", ph:"Blan-co"}, {sp:"Negro", en:"Black", ph:"Ne-gro"},
            {sp:"Rosa", en:"Pink", ph:"Ro-sa"}, {sp:"Naranja", en:"Orange", ph:"Na-ran-ha"},
            {sp:"Morado", en:"Purple", ph:"Mo-ra-do"}, {sp:"Gris", en:"Grey", ph:"Grees"},
            {sp:"Marrón", en:"Brown", ph:"Ma-rron"},
            // More Colors
            {sp:"Beige", en:"Beige", ph:"Bey-he"}, {sp:"Turquesa", en:"Turquoise", ph:"Tur-ke-sa"},
            {sp:"Dorado", en:"Gold", ph:"Do-ra-do"}, {sp:"Plateado", en:"Silver", ph:"Pla-te-a-do"},
            {sp:"Burdeos", en:"Burgundy", ph:"Bur-de-os"}, {sp:"Lila", en:"Lilac", ph:"Lee-la"},
            {sp:"Crema", en:"Cream", ph:"Kre-ma"}, {sp:"Magenta", en:"Magenta", ph:"Ma-hen-ta"},
            {sp:"Coral", en:"Coral", ph:"Ko-ral"}, {sp:"Índigo", en:"Indigo", ph:"Een-dee-go"},
            // Numbers 1–10
            {sp:"Uno", en:"One", ph:"Oo-no"}, {sp:"Dos", en:"Two", ph:"Dos"},
            {sp:"Tres", en:"Three", ph:"Tres"}, {sp:"Cuatro", en:"Four", ph:"Kwa-tro"},
            {sp:"Cinco", en:"Five", ph:"Seen-co"}, {sp:"Seis", en:"Six", ph:"Seys"},
            {sp:"Siete", en:"Seven", ph:"Sye-te"}, {sp:"Ocho", en:"Eight", ph:"O-cho"},
            {sp:"Nueve", en:"Nine", ph:"Nwe-be"}, {sp:"Diez", en:"Ten", ph:"Dyes"},
            // Numbers 11–20
            {sp:"Once", en:"Eleven", ph:"On-se"}, {sp:"Doce", en:"Twelve", ph:"Do-se"},
            {sp:"Trece", en:"Thirteen", ph:"Tre-se"}, {sp:"Catorce", en:"Fourteen", ph:"Ka-tor-se"},
            {sp:"Quince", en:"Fifteen", ph:"Keen-se"}, {sp:"Dieciséis", en:"Sixteen", ph:"Dye-see-seys"},
            {sp:"Diecisiete", en:"Seventeen", ph:"Dye-see-sye-te"}, {sp:"Dieciocho", en:"Eighteen", ph:"Dye-see-o-cho"},
            {sp:"Diecinueve", en:"Nineteen", ph:"Dye-see-nwe-be"}, {sp:"Veinte", en:"Twenty", ph:"Beyn-te"},
            // Numbers — Tens
            {sp:"Treinta", en:"Thirty", ph:"Treyn-ta"}, {sp:"Cuarenta", en:"Forty", ph:"Kwa-ren-ta"},
            {sp:"Cincuenta", en:"Fifty", ph:"Seen-kwen-ta"}, {sp:"Sesenta", en:"Sixty", ph:"Se-sen-ta"},
            {sp:"Setenta", en:"Seventy", ph:"Se-ten-ta"}, {sp:"Ochenta", en:"Eighty", ph:"O-chen-ta"},
            {sp:"Noventa", en:"Ninety", ph:"No-ben-ta"}, {sp:"Cien", en:"Hundred", ph:"Syen"}, {sp:"Mil", en:"Thousand", ph:"Meel"},
            // Family
            {sp:"Madre", en:"Mother", ph:"Ma-dre"}, {sp:"Padre", en:"Father", ph:"Pa-dre"},
            {sp:"Hermana", en:"Sister", ph:"Er-ma-na"}, {sp:"Hijo", en:"Son", ph:"Ee-ho"},
            {sp:"Hija", en:"Daughter", ph:"Ee-ha"}, {sp:"Abuelo", en:"Grandfather", ph:"A-bwe-lo"},
            {sp:"Abuela", en:"Grandmother", ph:"A-bwe-la"}, {sp:"Tío", en:"Uncle", ph:"Tee-o"},
            {sp:"Tía", en:"Aunt", ph:"Tee-a"}, {sp:"Primo", en:"Cousin (m)", ph:"Pree-mo"},
            // Animals
            {sp:"Pájaro", en:"Bird", ph:"Pa-ha-ro"}, {sp:"Pez", en:"Fish", ph:"Pes"},
            {sp:"Caballo", en:"Horse", ph:"Ca-ba-yo"}, {sp:"Vaca", en:"Cow", ph:"Ba-ca"},
            {sp:"Cerdo", en:"Pig", ph:"Ser-do"}, {sp:"Pollo", en:"Chicken", ph:"Po-yo"},
            {sp:"Conejo", en:"Rabbit", ph:"Co-ne-ho"}, {sp:"Ratón", en:"Mouse", ph:"Ra-ton"},
            {sp:"León", en:"Lion", ph:"Le-on"}, {sp:"Tigre", en:"Tiger", ph:"Tee-gre"},
            {sp:"Elefante", en:"Elephant", ph:"E-le-fan-te"}, {sp:"Oso", en:"Bear", ph:"O-so"},
            // Food & Drink
            {sp:"Arroz", en:"Rice", ph:"A-rros"}, {sp:"Pan", en:"Bread", ph:"Pan"},
            {sp:"Carne", en:"Meat", ph:"Car-ne"}, {sp:"Huevo", en:"Egg", ph:"We-bo"},
            {sp:"Queso", en:"Cheese", ph:"Ke-so"}, {sp:"Sal", en:"Salt", ph:"Sal"},
            {sp:"Azúcar", en:"Sugar", ph:"A-soo-car"}, {sp:"Café", en:"Coffee", ph:"Ca-feh"},
            {sp:"Jugo", en:"Juice", ph:"Hoo-go"}, {sp:"Vino", en:"Wine", ph:"Bee-no"},
            {sp:"Cerveza", en:"Beer", ph:"Ser-be-sa"}, {sp:"Sopa", en:"Soup", ph:"So-pa"},
            // Nature
            {sp:"Árbol", en:"Tree", ph:"Ar-bol"}, {sp:"Montaña", en:"Mountain", ph:"Mon-ta-nya"},
            {sp:"Río", en:"River", ph:"Ree-o"}, {sp:"Mar", en:"Sea", ph:"Mar"},
            {sp:"Lluvia", en:"Rain", ph:"Yoo-bya"}, {sp:"Viento", en:"Wind", ph:"Byen-to"},
            {sp:"Nieve", en:"Snow", ph:"Nye-be"}, {sp:"Fuego", en:"Fire", ph:"Fwe-go"},
            {sp:"Tierra", en:"Earth/Land", ph:"Tye-rra"}, {sp:"Piedra", en:"Stone", ph:"Pye-dra"},
            {sp:"Arena", en:"Sand", ph:"A-re-na"}, {sp:"Nube", en:"Cloud", ph:"Noo-be"},
            // Common adjectives
            {sp:"Grande", en:"Big", ph:"Gran-de"}, {sp:"Pequeño", en:"Small", ph:"Pe-ke-nyo"},
            {sp:"Nuevo", en:"New", ph:"Nwe-bo"}, {sp:"Viejo", en:"Old", ph:"Bye-ho"},
            {sp:"Bueno", en:"Good", ph:"Bwe-no"}, {sp:"Malo", en:"Bad", ph:"Ma-lo"},
            {sp:"Rápido", en:"Fast", ph:"Ra-pee-do"}, {sp:"Lento", en:"Slow", ph:"Len-to"},
            {sp:"Caliente", en:"Hot", ph:"Ca-lyen-te"}, {sp:"Frío", en:"Cold", ph:"Free-o"},
            {sp:"Feliz", en:"Happy", ph:"Fe-lees"}, {sp:"Triste", en:"Sad", ph:"Trees-te"},
            // Common verbs
            {sp:"Comer", en:"To eat", ph:"Co-mer"}, {sp:"Beber", en:"To drink", ph:"Be-ber"},
            {sp:"Dormir", en:"To sleep", ph:"Dor-meer"}, {sp:"Hablar", en:"To speak", ph:"A-blar"},
            {sp:"Caminar", en:"To walk", ph:"Ca-mee-nar"}, {sp:"Correr", en:"To run", ph:"Co-rrer"},
            {sp:"Leer", en:"To read", ph:"Le-er"}, {sp:"Escribir", en:"To write", ph:"Es-cree-beer"},
            {sp:"Ver", en:"To see", ph:"Ber"}, {sp:"Escuchar", en:"To listen", ph:"Es-coo-char"},
            // Places
            {sp:"Escuela", en:"School", ph:"Es-kwe-la"}, {sp:"Tienda", en:"Shop", ph:"Tyen-da"},
            {sp:"Banco", en:"Bank", ph:"Ban-co"}, {sp:"Hospital", en:"Hospital", ph:"Os-pee-tal"},
            {sp:"Iglesia", en:"Church", ph:"Ee-gle-sya"}, {sp:"Playa", en:"Beach", ph:"Pla-ya"},
            {sp:"Parque", en:"Park", ph:"Par-ke"}, {sp:"Aeropuerto", en:"Airport", ph:"A-e-ro-pwer-to"},
        ],
        medium: [
            // Original entries
            {sp:"Zapato", en:"Shoe", ph:"Sa-pa-to"}, {sp:"Ventana", en:"Window", ph:"Ven-ta-na"},
            {sp:"Trabajo", en:"Work", ph:"Tra-ba-ho"}, {sp:"Cuchara", en:"Spoon", ph:"Koo-cha-ra"},
            {sp:"Mañana", en:"Tomorrow", ph:"Ma-nya-na"}, {sp:"Olvidar", en:"To forget", ph:"Ol-vee-dar"},
            {sp:"Recordar", en:"To remember", ph:"Re-cor-dar"}, {sp:"Ciudad", en:"City", ph:"Syoo-dad"},
            {sp:"Dinero", en:"Money", ph:"Dee-ne-ro"}, {sp:"Hermano", en:"Brother", ph:"Er-ma-no"},
            // NEW medium — Verbs
            {sp:"Encontrar", en:"To find", ph:"En-con-trar"}, {sp:"Necesitar", en:"To need", ph:"Ne-se-see-tar"},
            {sp:"Conseguir", en:"To manage/get", ph:"Con-se-gheer"}, {sp:"Entender", en:"To understand", ph:"En-ten-der"},
            {sp:"Conocer", en:"To know (person)", ph:"Co-no-ser"}, {sp:"Saber", en:"To know (fact)", ph:"Sa-ber"},
            {sp:"Querer", en:"To want/love", ph:"Ke-rer"}, {sp:"Poder", en:"To be able to", ph:"Po-der"},
            {sp:"Deber", en:"To owe/should", ph:"De-ber"}, {sp:"Traer", en:"To bring", ph:"Tra-er"},
            {sp:"Llevar", en:"To carry/take", ph:"Ye-bar"}, {sp:"Pedir", en:"To ask for", ph:"Pe-deer"},
            {sp:"Preguntar", en:"To ask (question)", ph:"Pre-goon-tar"}, {sp:"Responder", en:"To answer", ph:"Res-pon-der"},
            {sp:"Ayudar", en:"To help", ph:"A-yoo-dar"}, {sp:"Empezar", en:"To begin", ph:"Em-pe-sar"},
            {sp:"Terminar", en:"To finish", ph:"Ter-mee-nar"}, {sp:"Continuar", en:"To continue", ph:"Con-tee-nwar"},
            {sp:"Parar", en:"To stop", ph:"Pa-rar"}, {sp:"Cambiar", en:"To change", ph:"Cam-byar"},
            {sp:"Mejorar", en:"To improve", ph:"Me-ho-rar"}, {sp:"Perder", en:"To lose", ph:"Per-der"},
            {sp:"Ganar", en:"To win/earn", ph:"Ga-nar"}, {sp:"Intentar", en:"To try", ph:"Een-ten-tar"},
            {sp:"Esperar", en:"To wait/hope", ph:"Es-pe-rar"}, {sp:"Volver", en:"To return", ph:"Bol-ber"},
            {sp:"Salir", en:"To leave/go out", ph:"Sa-leer"}, {sp:"Entrar", en:"To enter", ph:"En-trar"},
            {sp:"Abrir", en:"To open", ph:"A-breer"}, {sp:"Cerrar", en:"To close", ph:"Se-rrar"},
            {sp:"Comprar", en:"To buy", ph:"Com-prar"}, {sp:"Vender", en:"To sell", ph:"Ben-der"},
            {sp:"Pagar", en:"To pay", ph:"Pa-gar"}, {sp:"Vivir", en:"To live", ph:"Bee-beer"},
            {sp:"Viajar", en:"To travel", ph:"Bya-har"}, {sp:"Pensar", en:"To think", ph:"Pen-sar"},
            {sp:"Creer", en:"To believe", ph:"Cre-er"}, {sp:"Sentir", en:"To feel", ph:"Sen-teer"},
            // Nouns — Home & Objects
            {sp:"Sofá", en:"Sofa", ph:"So-fa"}, {sp:"Cama", en:"Bed", ph:"Ca-ma"},
            {sp:"Almohada", en:"Pillow", ph:"Al-mo-a-da"}, {sp:"Manta", en:"Blanket", ph:"Man-ta"},
            {sp:"Armario", en:"Wardrobe", ph:"Ar-ma-ryo"}, {sp:"Cajón", en:"Drawer", ph:"Ca-hon"},
            {sp:"Nevera", en:"Refrigerator", ph:"Ne-be-ra"}, {sp:"Cocina", en:"Kitchen/Stove", ph:"Co-see-na"},
            {sp:"Microondas", en:"Microwave", ph:"Mee-cro-on-das"}, {sp:"Ducha", en:"Shower", ph:"Doo-cha"},
            {sp:"Baño", en:"Bathroom", ph:"Ba-nyo"}, {sp:"Jardín", en:"Garden", ph:"Har-deen"},
            {sp:"Balcón", en:"Balcony", ph:"Bal-con"}, {sp:"Escalera", en:"Stairs", ph:"Es-ca-le-ra"},
            {sp:"Techo", en:"Ceiling/Roof", ph:"Te-cho"}, {sp:"Pared", en:"Wall", ph:"Pa-red"},
            {sp:"Suelo", en:"Floor/Ground", ph:"Swe-lo"},
            // Transport & City
            {sp:"Autobús", en:"Bus", ph:"Ow-to-boos"}, {sp:"Metro", en:"Subway/Metro", ph:"Me-tro"},
            {sp:"Tren", en:"Train", ph:"Tren"}, {sp:"Avión", en:"Airplane", ph:"A-byon"},
            {sp:"Taxi", en:"Taxi", ph:"Tax-ee"}, {sp:"Moto", en:"Motorcycle", ph:"Mo-to"},
            {sp:"Barrio", en:"Neighbourhood", ph:"Ba-rryo"}, {sp:"Plaza", en:"Square/Plaza", ph:"Pla-sa"},
            {sp:"Esquina", en:"Corner", ph:"Es-kee-na"}, {sp:"Semáforo", en:"Traffic light", ph:"Se-ma-fo-ro"},
            {sp:"Acera", en:"Pavement/Sidewalk", ph:"A-se-ra"}, {sp:"Puente", en:"Bridge", ph:"Pwen-te"},
            // Adjectives
            {sp:"Cansado", en:"Tired", ph:"Can-sa-do"}, {sp:"Ocupado", en:"Busy", ph:"O-coo-pa-do"},
            {sp:"Libre", en:"Free", ph:"Lee-bre"}, {sp:"Lleno", en:"Full", ph:"Ye-no"},
            {sp:"Vacío", en:"Empty", ph:"Ba-see-o"}, {sp:"Pesado", en:"Heavy", ph:"Pe-sa-do"},
            {sp:"Ligero", en:"Light (weight)", ph:"Lee-he-ro"}, {sp:"Ancho", en:"Wide", ph:"An-cho"},
            {sp:"Estrecho", en:"Narrow", ph:"Es-tre-cho"}, {sp:"Alto", en:"Tall/High", ph:"Al-to"},
            {sp:"Bajo", en:"Short/Low", ph:"Ba-ho"}, {sp:"Gordo", en:"Fat", ph:"Gor-do"},
            {sp:"Delgado", en:"Thin/Slim", ph:"Del-ga-do"}, {sp:"Fuerte", en:"Strong", ph:"Fwer-te"},
            {sp:"Débil", en:"Weak", ph:"De-beel"}, {sp:"Rico", en:"Rich", ph:"Ree-co"},
            {sp:"Pobre", en:"Poor", ph:"Po-bre"}, {sp:"Solo", en:"Alone", ph:"So-lo"},
            {sp:"Juntos", en:"Together", ph:"Hoon-tos"}, {sp:"Diferente", en:"Different", ph:"Dee-fe-ren-te"},
            {sp:"Igual", en:"Equal/Same", ph:"Ee-gwal"}, {sp:"Seguro", en:"Safe/Secure", ph:"Se-goo-ro"},
            {sp:"Peligroso", en:"Dangerous", ph:"Pe-lee-gro-so"}, {sp:"Famoso", en:"Famous", ph:"Fa-mo-so"},
            {sp:"Extraño", en:"Strange", ph:"Es-tra-nyo"}, {sp:"Estresado", en:"Stressed", ph:"Es-tre-sa-do"},
            // Food & Meals
            {sp:"Almuerzo", en:"Lunch", ph:"Al-mwer-so"}, {sp:"Cena", en:"Dinner", ph:"Se-na"},
            {sp:"Desayuno", en:"Breakfast", ph:"De-sa-yoo-no"}, {sp:"Postre", en:"Dessert", ph:"Pos-tre"},
            {sp:"Ensalada", en:"Salad", ph:"En-sa-la-da"}, {sp:"Pasta", en:"Pasta", ph:"Pas-ta"},
            {sp:"Pastel", en:"Cake/Pie", ph:"Pas-tel"}, {sp:"Galleta", en:"Cookie/Biscuit", ph:"Ga-ye-ta"},
            {sp:"Helado", en:"Ice cream", ph:"E-la-do"}, {sp:"Mantequilla", en:"Butter", ph:"Man-te-kee-ya"},
            {sp:"Aceite", en:"Oil", ph:"A-sey-te"}, {sp:"Vinagre", en:"Vinegar", ph:"Bee-na-gre"},
            {sp:"Pimienta", en:"Pepper", ph:"Pee-myen-ta"}, {sp:"Ajo", en:"Garlic", ph:"A-ho"},
            {sp:"Cebolla", en:"Onion", ph:"Se-bo-ya"}, {sp:"Tomate", en:"Tomato", ph:"To-ma-te"},
            {sp:"Patata", en:"Potato", ph:"Pa-ta-ta"}, {sp:"Zanahoria", en:"Carrot", ph:"Sa-na-o-rya"},
            {sp:"Lechuga", en:"Lettuce", ph:"Le-choo-ga"}, {sp:"Fresa", en:"Strawberry", ph:"Fre-sa"},
            // Time & Calendar
            {sp:"Ayer", en:"Yesterday", ph:"A-yer"}, {sp:"Hoy", en:"Today", ph:"Oy"},
            {sp:"Semana", en:"Week", ph:"Se-ma-na"}, {sp:"Mes", en:"Month", ph:"Mes"},
            {sp:"Año", en:"Year", ph:"A-nyo"}, {sp:"Hora", en:"Hour", ph:"O-ra"},
            {sp:"Minuto", en:"Minute", ph:"Mee-noo-to"}, {sp:"Segundo", en:"Second", ph:"Se-goon-do"},
            {sp:"Lunes", en:"Monday", ph:"Loo-nes"}, {sp:"Martes", en:"Tuesday", ph:"Mar-tes"},
            {sp:"Miércoles", en:"Wednesday", ph:"Myer-co-les"}, {sp:"Jueves", en:"Thursday", ph:"Hwe-bes"},
            {sp:"Viernes", en:"Friday", ph:"Byer-nes"}, {sp:"Sábado", en:"Saturday", ph:"Sa-ba-do"},
            {sp:"Domingo", en:"Sunday", ph:"Do-meen-go"},
            // Emotions
            {sp:"Miedo", en:"Fear", ph:"Mye-do"}, {sp:"Rabia", en:"Anger", ph:"Ra-bya"},
            {sp:"Alegría", en:"Joy", ph:"A-le-gree-a"}, {sp:"Tristeza", en:"Sadness", ph:"Trees-te-sa"},
            {sp:"Sorpresa", en:"Surprise", ph:"Sor-pre-sa"}, {sp:"Vergüenza", en:"Shame", ph:"Ber-gwen-sa"},
            {sp:"Orgullo", en:"Pride", ph:"Or-goo-yo"}, {sp:"Celos", en:"Jealousy", ph:"Se-los"},
            {sp:"Envidia", en:"Envy", ph:"En-bee-dya"}, {sp:"Ansiedad", en:"Anxiety", ph:"An-sye-dad"},
            // Health
            {sp:"Médico", en:"Doctor", ph:"Me-dee-co"}, {sp:"Medicina", en:"Medicine", ph:"Me-dee-see-na"},
            {sp:"Dolor", en:"Pain", ph:"Do-lor"}, {sp:"Fiebre", en:"Fever", ph:"Fye-bre"},
            {sp:"Tos", en:"Cough", ph:"Tos"}, {sp:"Resfriado", en:"Cold (illness)", ph:"Res-free-a-do"},
            {sp:"Cansancio", en:"Fatigue", ph:"Can-san-syo"}, {sp:"Salud", en:"Health", ph:"Sa-lood"},
        ],
        hard: [
            // Original entries
            {sp:"Desarrollo", en:"Development", ph:"De-sa-rro-yo"},
            {sp:"Responsabilidad", en:"Responsibility", ph:"Res-pon-sa-bee-lee-dad"},
            {sp:"Conocimiento", en:"Knowledge", ph:"Co-no-see-myen-to"},
            {sp:"Pensamiento", en:"Thought", ph:"Pen-sa-myen-to"},
            {sp:"Extraordinario", en:"Extraordinary", ph:"Eks-tra-or-dee-na-ryo"},
            // NEW hard words — Abstract nouns
            {sp:"Conciencia", en:"Conscience/Awareness", ph:"Con-syen-sya"}, {sp:"Comportamiento", en:"Behaviour", ph:"Com-por-ta-myen-to"},
            {sp:"Establecimiento", en:"Establishment", ph:"Es-ta-ble-see-myen-to"}, {sp:"Acontecimiento", en:"Event/Occurrence", ph:"A-con-te-see-myen-to"},
            {sp:"Circunstancia", en:"Circumstance", ph:"Seer-coon-stan-sya"}, {sp:"Consecuencia", en:"Consequence", ph:"Con-se-kwen-sya"},
            {sp:"Experiencia", en:"Experience", ph:"Eks-pe-ryen-sya"}, {sp:"Influencia", en:"Influence", ph:"Een-flwen-sya"},
            {sp:"Independencia", en:"Independence", ph:"Een-de-pen-den-sya"}, {sp:"Transparencia", en:"Transparency", ph:"Trans-pa-ren-sya"},
            {sp:"Persistencia", en:"Persistence", ph:"Per-sees-ten-sya"}, {sp:"Competencia", en:"Competence", ph:"Com-pe-ten-sya"},
            {sp:"Curiosidad", en:"Curiosity", ph:"Coo-ryo-see-dad"}, {sp:"Dificultad", en:"Difficulty", ph:"Dee-fee-cool-tad"},
            {sp:"Oportunidad", en:"Opportunity", ph:"O-por-too-nee-dad"}, {sp:"Necesidad", en:"Necessity", ph:"Ne-se-see-dad"},
            {sp:"Posibilidad", en:"Possibility", ph:"Po-see-bee-lee-dad"}, {sp:"Realidad", en:"Reality", ph:"Re-a-lee-dad"},
            {sp:"Personalidad", en:"Personality", ph:"Per-so-na-lee-dad"}, {sp:"Identidad", en:"Identity", ph:"Ee-den-tee-dad"},
            {sp:"Complejidad", en:"Complexity", ph:"Com-ple-hee-dad"}, {sp:"Humanidad", en:"Humanity", ph:"Oo-ma-nee-dad"},
            {sp:"Generosidad", en:"Generosity", ph:"He-ne-ro-see-dad"}, {sp:"Creatividad", en:"Creativity", ph:"Cre-a-tee-bee-dad"},
            {sp:"Solidaridad", en:"Solidarity", ph:"So-lee-da-ree-dad"}, {sp:"Sustentabilidad", en:"Sustainability", ph:"Soos-ten-ta-bee-lee-dad"},
            {sp:"Reconocimiento", en:"Recognition", ph:"Re-co-no-see-myen-to"}, {sp:"Perfeccionamiento", en:"Perfecting/Improvement", ph:"Per-fek-syo-na-myen-to"},
            // Complex verbs
            {sp:"Comprometerse", en:"To commit oneself", ph:"Com-pro-me-ter-se"}, {sp:"Establecer", en:"To establish", ph:"Es-ta-ble-ser"},
            {sp:"Desarrollar", en:"To develop", ph:"De-sa-rro-yar"}, {sp:"Manifestar", en:"To manifest", ph:"Ma-nee-fes-tar"},
            {sp:"Implementar", en:"To implement", ph:"Eem-ple-men-tar"}, {sp:"Administrar", en:"To manage/administer", ph:"Ad-mee-nees-trar"},
            {sp:"Comunicar", en:"To communicate", ph:"Co-moo-nee-car"}, {sp:"Demostrar", en:"To demonstrate", ph:"De-mos-trar"},
            {sp:"Representar", en:"To represent", ph:"Re-pre-sen-tar"}, {sp:"Interpretar", en:"To interpret", ph:"Een-ter-pre-tar"},
            {sp:"Transformar", en:"To transform", ph:"Trans-for-mar"}, {sp:"Conquistar", en:"To conquer/achieve", ph:"Con-kees-tar"},
            {sp:"Abandonar", en:"To abandon", ph:"A-ban-do-nar"}, {sp:"Superar", en:"To overcome", ph:"Soo-pe-rar"},
            {sp:"Imaginar", en:"To imagine", ph:"Ee-ma-hee-nar"}, {sp:"Contribuir", en:"To contribute", ph:"Con-tree-boo-eer"},
            {sp:"Recomendar", en:"To recommend", ph:"Re-co-men-dar"}, {sp:"Considerar", en:"To consider", ph:"Con-see-de-rar"},
            {sp:"Comprender", en:"To understand (fully)", ph:"Com-pren-der"}, {sp:"Sorprender", en:"To surprise", ph:"Sor-pren-der"},
            // Hard adjectives
            {sp:"Impresionante", en:"Impressive", ph:"Eem-pre-syo-nan-te"}, {sp:"Desafiante", en:"Challenging", ph:"De-sa-fyan-te"},
            {sp:"Inconveniente", en:"Inconvenient", ph:"Een-con-be-nyen-te"}, {sp:"Sorprendente", en:"Surprising", ph:"Sor-pren-den-te"},
            {sp:"Preocupante", en:"Worrying", ph:"Pre-o-coo-pan-te"}, {sp:"Reconocible", en:"Recognisable", ph:"Re-co-no-see-ble"},
            {sp:"Increíble", en:"Unbelievable", ph:"Een-cre-ee-ble"}, {sp:"Indispensable", en:"Indispensable", ph:"Een-dees-pen-sa-ble"},
            {sp:"Irresponsable", en:"Irresponsible", ph:"Ee-rres-pon-sa-ble"}, {sp:"Incomprensible", en:"Incomprehensible", ph:"Een-com-pren-see-ble"},
            {sp:"Interminable", en:"Endless", ph:"Een-ter-mee-na-ble"}, {sp:"Imprescindible", en:"Essential/Indispensable", ph:"Eem-pres-seen-dee-ble"},
            // Science, society & culture
            {sp:"Sociedad", en:"Society", ph:"So-sye-dad"}, {sp:"Cultura", en:"Culture", ph:"Cool-too-ra"},
            {sp:"Ciencia", en:"Science", ph:"Syen-sya"}, {sp:"Tecnología", en:"Technology", ph:"Tek-no-lo-hee-a"},
            {sp:"Filosofía", en:"Philosophy", ph:"Fee-lo-so-fee-a"}, {sp:"Arte", en:"Art", ph:"Ar-te"},
            {sp:"Religión", en:"Religion", ph:"Re-lee-hyon"}, {sp:"Psicología", en:"Psychology", ph:"Psee-co-lo-hee-a"},
            {sp:"Medicina", en:"Medicine (field)", ph:"Me-dee-see-na"}, {sp:"Física", en:"Physics", ph:"Fee-see-ca"},
            {sp:"Química", en:"Chemistry", ph:"Kee-mee-ca"}, {sp:"Matemáticas", en:"Mathematics", ph:"Ma-te-ma-tee-cas"},
            {sp:"Literatura", en:"Literature", ph:"Lee-te-ra-too-ra"}, {sp:"Música", en:"Music", ph:"Moo-see-ca"},
            {sp:"Arquitectura", en:"Architecture", ph:"Ar-kee-tek-too-ra"}, {sp:"Agricultura", en:"Agriculture", ph:"A-gree-cool-too-ra"},
            {sp:"Industria", en:"Industry", ph:"Een-doos-trya"}, {sp:"Comercio", en:"Commerce", ph:"Co-mer-syo"},
            {sp:"Educación", en:"Education", ph:"E-doo-ca-syon"}, {sp:"Investigación", en:"Research/Investigation", ph:"Een-bes-tee-ga-syon"},
            {sp:"Avance", en:"Advance/Progress", ph:"A-ban-se"}, {sp:"Crecimiento", en:"Growth", ph:"Cre-see-myen-to"},
            {sp:"Cambio", en:"Change", ph:"Cam-byo"}, {sp:"Influjo", en:"Influx/Influence", ph:"Een-floo-ho"},
            {sp:"Dilema", en:"Dilemma", ph:"Dee-le-ma"}, {sp:"Solución", en:"Solution", ph:"So-loo-syon"},
            {sp:"Resultado", en:"Result/Outcome", ph:"Re-sool-ta-do"}, {sp:"Causa", en:"Cause", ph:"Cow-sa"},
            {sp:"Propósito", en:"Purpose/Goal", ph:"Pro-po-see-to"}, {sp:"Método", en:"Method", ph:"Me-to-do"},
            {sp:"Situación", en:"Situation", ph:"See-twa-syon"}, {sp:"Motivo", en:"Reason/Motive", ph:"Mo-tee-bo"},
            {sp:"Relación", en:"Relationship", ph:"Re-la-syon"}, {sp:"Postura", en:"Stance/Posture", ph:"Pos-too-ra"}, {sp:"Derecho", en:"Right/Law", ph:"De-re-cho"},
        ],
        vhard: [
            // Original entries
            {sp:"Desafortunadamente", en:"Unfortunately", ph:"De-sa-for-too-na-da-men-te"},
            {sp:"Electroencefalografista", en:"EEG Technician", ph:"E-lek-tro-en-se-fa-lo-gra-fees-ta"},
            {sp:"Esternocleidomastoideo", en:"Sternocleidomastoid (neck muscle)", ph:"Es-ter-no-kley-do-mas-toy-de-o"},
            {sp:"Paralelepípedo", en:"Parallelepiped", ph:"Pa-ra-le-le-pee-pe-do"},
            // NEW vhard words
            {sp:"Anticonstitucionalmente", en:"Unconstitutionally", ph:"An-tee-con-stee-too-syo-nal-men-te"},
            {sp:"Internacionalización", en:"Internationalisation", ph:"Een-ter-na-syo-na-lee-sa-syon"},
            {sp:"Responsabilizarse", en:"To take responsibility (reflexive)", ph:"Res-pon-sa-bee-lee-sar-se"},
            {sp:"Inconstitucionalidad", en:"Unconstitutionality", ph:"Een-con-stee-too-syo-na-lee-dad"},
            {sp:"Telecomunicaciones", en:"Telecommunications", ph:"Te-le-co-moo-nee-ca-syo-nes"},
            {sp:"Descontextualización", en:"Decontextualisation", ph:"Des-con-tex-too-a-lee-sa-syon"},
            {sp:"Imprevisibilidad", en:"Unpredictability", ph:"Eem-pre-bee-see-bee-lee-dad"},
            {sp:"Indiscriminadamente", en:"Indiscriminately", ph:"Een-dees-cree-mee-na-da-men-te"},
            {sp:"Institucionalización", en:"Institutionalisation", ph:"Ees-tee-too-syo-na-lee-sa-syon"},
            {sp:"Multiculturalismo", en:"Multiculturalism", ph:"Mool-tee-cul-too-ra-lees-mo"},
            {sp:"Contemporaneidad", en:"Contemporaneity", ph:"Con-tem-po-ra-ne-ee-dad"},
            {sp:"Transdisciplinariedad", en:"Transdisciplinarity", ph:"Trans-dees-see-plee-na-rye-dad"},
            {sp:"Otorrinolaringólogo", en:"ENT Doctor", ph:"O-to-rree-no-la-reen-go-lo-go"},
            {sp:"Hipopotomonstrosesquipedaliofobia", en:"Fear of long words", ph:"Ee-po-po-to-mon-stro-ses-kee-pe-da-lyo-fo-bya"},
        ]
    },
    phrases: {
        easy: [
            {sp:"¿Cómo estás?", en:"How are you?", ph:"Co-mo es-tas"}, {sp:"¿Cómo te llamas?", en:"What is your name?", ph:"Co-mo te ya-mas"},
            {sp:"Me llamo...", en:"My name is...", ph:"Me ya-mo"}, {sp:"Buenos días", en:"Good morning", ph:"Bwe-nos dee-as"},
            {sp:"Buenas tardes", en:"Good afternoon", ph:"Bwe-nas tar-des"}, {sp:"Buenas noches", en:"Good evening/night", ph:"Bwe-nas no-ches"},
            {sp:"¡Adiós!", en:"Goodbye!", ph:"A-dyos"}, {sp:"¡Hasta luego!", en:"See you later!", ph:"As-ta lwe-go"},
            {sp:"¡Hasta mañana!", en:"See you tomorrow!", ph:"As-ta ma-nya-na"}, {sp:"Por favor", en:"Please", ph:"Por fa-bor"},
            {sp:"De nada", en:"You're welcome", ph:"De na-da"}, {sp:"Con permiso", en:"Excuse me", ph:"Con per-mee-so"},
            {sp:"Lo siento", en:"I'm sorry", ph:"Lo syen-to"}, {sp:"¿Todo bien?", en:"Everything okay?", ph:"To-do byen"},
            {sp:"¡Todo bien!", en:"Everything's fine!", ph:"To-do byen"}, {sp:"Sí", en:"Yes", ph:"See"},
            {sp:"No", en:"No", ph:"No"}, {sp:"Tal vez", en:"Maybe", ph:"Tal bes"},
            {sp:"No sé", en:"I don't know", ph:"No seh"}, {sp:"Entiendo", en:"I understand", ph:"En-tyen-do"},
            {sp:"No entiendo", en:"I don't understand", ph:"No en-tyen-do"}, {sp:"¿Puede repetir?", en:"Can you repeat?", ph:"Pwe-de re-pe-teer"},
            {sp:"Hable más despacio", en:"Speak more slowly", ph:"A-ble mas des-pa-syo"}, {sp:"¿Dónde está el baño?", en:"Where is the bathroom?", ph:"Don-de es-ta el ba-nyo"},
            {sp:"¿Cuánto cuesta?", en:"How much does it cost?", ph:"Kwan-to kwes-ta"}, {sp:"Quisiera...", en:"I would like...", ph:"Kee-sye-ra"},
            {sp:"¿Qué hora es?", en:"What time is it?", ph:"Ke o-ra es"}, {sp:"¡Mucho gusto!", en:"Nice to meet you!", ph:"Moo-cho goos-to"},
            {sp:"¡Feliz cumpleaños!", en:"Happy birthday!", ph:"Fe-lees coom-ple-a-nyos"}, {sp:"¡Feliz Navidad!", en:"Merry Christmas!", ph:"Fe-lees na-bee-dad"},
            {sp:"¡Buena suerte!", en:"Good luck!", ph:"Bwe-na swer-te"}, {sp:"¡Enhorabuena!", en:"Congratulations!", ph:"En-o-ra-bwe-na"},
            {sp:"¡Claro!", en:"Of course!", ph:"Cla-ro"}, {sp:"¡Por supuesto!", en:"Of course!/Certainly!", ph:"Por soo-pwes-to"},
            {sp:"Tengo hambre", en:"I'm hungry", ph:"Ten-go am-bre"}, {sp:"Tengo sed", en:"I'm thirsty", ph:"Ten-go sed"},
            {sp:"Tengo sueño", en:"I'm sleepy", ph:"Ten-go swe-nyo"}, {sp:"¿Me puede ayudar?", en:"Can you help me?", ph:"Me pwe-de a-yoo-dar"},
            // More easy phrases
            {sp:"¡Qué guay!", en:"How cool!", ph:"Ke gwai"}, {sp:"¡Qué pena!", en:"What a shame!", ph:"Ke pe-na"},
            {sp:"¡Qué bonito/a!", en:"How beautiful!", ph:"Ke bo-nee-to/ta"}, {sp:"¡Qué rico!", en:"How delicious!", ph:"Ke ree-co"},
            {sp:"¡Vamos!", en:"Let's go!", ph:"Ba-mos"}, {sp:"¡Venga!", en:"Come on!/Let's go! (Spain)", ph:"Ben-ga"},
            {sp:"¡Que te vaya bien!", en:"Hope it goes well for you!", ph:"Ke te ba-ya byen"}, {sp:"¡Buen provecho!", en:"Enjoy your meal!", ph:"Bwen pro-be-cho"},
            {sp:"¡Buen viaje!", en:"Have a good trip!", ph:"Bwen bya-he"}, {sp:"Estoy bien, gracias.", en:"I'm fine, thank you.", ph:"Es-toy byen gra-syas"},
            {sp:"¿De dónde eres?", en:"Where are you from?", ph:"De don-de e-res"}, {sp:"Soy de...", en:"I'm from...", ph:"Soy de"},
            {sp:"No te preocupes", en:"Don't worry", ph:"No te pre-o-koo-pes"}, {sp:"¡Salud!", en:"Cheers!/Bless you!", ph:"Sa-lood"},
        ],
        medium: [
            {sp:"Llevo dos años viviendo en España", en:"I have been living in Spain for two years", ph:"Ye-bo dos a-nyos bee-byen-do en Es-pa-nya"},
            {sp:"¿Puede ayudarme, por favor?", en:"Can you help me, please?", ph:"Pwe-de a-yoo-dar-me por fa-bor"},
            {sp:"¿Cuál es el mejor restaurante por aquí?", en:"What is the best restaurant around here?", ph:"Kwal es el me-hor res-tow-ran-te por a-kee"},
            {sp:"Estoy aprendiendo español", en:"I am learning Spanish", ph:"Es-toy a-pren-dyen-do es-pa-nyol"},
            {sp:"No es exactamente así", en:"That's not quite right", ph:"No es ek-sak-ta-men-te a-see"},
            {sp:"Eso depende de la situación", en:"That depends on the situation", ph:"E-so de-pen-de de la see-twa-syon"},
            {sp:"¿Puedo llamarte más tarde?", en:"Can I call you later?", ph:"Pwe-do ya-mar-te mas tar-de"},
            {sp:"¿Qué te parece esto?", en:"What do you think about this?", ph:"Ke te pa-re-se es-to"},
            {sp:"Necesito una hora para terminar", en:"I need an hour to finish", ph:"Ne-se-see-to oo-na o-ra pa-ra ter-mee-nar"},
            {sp:"¿Has visitado Madrid alguna vez?", en:"Have you ever visited Madrid?", ph:"As bee-see-ta-do Ma-dreed al-goo-na bes"},
            {sp:"¿Quedamos la semana que viene?", en:"Shall we meet next week?", ph:"Ke-da-mos la se-ma-na ke bye-ne"},
            {sp:"Prefiero quedarme en casa hoy", en:"I prefer to stay home today", ph:"Pre-fye-ro ke-dar-me en ca-sa oy"},
            {sp:"¿Hablas algún otro idioma?", en:"Do you speak any other language?", ph:"A-blas al-goon o-tro ee-dyo-ma"},
            {sp:"Esto es muy importante para mí", en:"This is very important to me", ph:"Es-to es mwee eem-por-tan-te pa-ra mee"},
            {sp:"¿Qué tipo de música te gusta?", en:"What kind of music do you like?", ph:"Ke tee-po de moo-see-ca te goos-ta"},
            {sp:"Tengo dolor de cabeza", en:"I have a headache", ph:"Ten-go do-lor de ca-be-sa"},
            {sp:"¿Cuánto tiempo se tarda en llegar?", en:"How long does it take to get there?", ph:"Kwan-to tyen-po se tar-da en ye-gar"},
            {sp:"¿Me puedes dar una pista?", en:"Can you give me a hint?", ph:"Me pwe-des dar oo-na pees-ta"},
            {sp:"Estaba pensando en ti", en:"I was thinking about you", ph:"Es-ta-ba pen-san-do en tee"},
            {sp:"Eso me hace muy feliz", en:"This makes me very happy", ph:"E-so me a-se mwee fe-lees"},
            {sp:"¿Quieres tomar algo?", en:"Would you like something to drink?", ph:"Kye-res to-mar al-go"},
            {sp:"No puedo dormir", en:"I can't sleep", ph:"No pwe-do dor-meer"},
            {sp:"La cuenta, por favor", en:"The bill, please", ph:"La kwen-ta por fa-bor"},
            {sp:"¿Hay algún problema?", en:"Is there any problem?", ph:"Ay al-goon pro-ble-ma"},
            {sp:"Lo pensaré", en:"I will think about it", ph:"Lo pen-sa-reh"},
            {sp:"¿Con quién vives?", en:"Who do you live with?", ph:"Con kyen bee-bes"},
            {sp:"¿Qué día es hoy?", en:"What day is today?", ph:"Ke dee-a es oy"},
            {sp:"El autobús viene a las nueve", en:"The bus comes at nine", ph:"El ow-to-boos bye-ne a las nwe-be"},
            {sp:"¿Ya has comido hoy?", en:"Have you eaten today?", ph:"Ya as co-mee-do oy"},
            {sp:"No me acuerdo de eso", en:"I don't remember that", ph:"No me a-kwer-do de e-so"},
            // More medium phrases
            {sp:"¿Dónde trabajas?", en:"Where do you work?", ph:"Don-de tra-ba-has"},
            {sp:"¿Cuánto tiempo llevas estudiando español?", en:"How long have you been studying Spanish?", ph:"Kwan-to tyen-po ye-bas es-too-dyan-do es-pa-nyol"},
            {sp:"Me gusta mucho la música española", en:"I really like Spanish music", ph:"Me goos-ta moo-cho la moo-see-ca es-pa-nyo-la"},
            {sp:"¿Me lo puedes señalar en el mapa?", en:"Can you point it out on the map?", ph:"Me lo pwe-des se-nya-lar en el ma-pa"},
            {sp:"¿Hay algo vegetariano en el menú?", en:"Is there anything vegetarian on the menu?", ph:"Ay al-go be-he-ta-rya-no en el me-noo"},
            {sp:"Necesito cambiar dinero", en:"I need to exchange money", ph:"Ne-se-see-to kam-byar dee-ne-ro"},
            {sp:"¿Me puedes dar un descuento?", en:"Can you give me a discount?", ph:"Me pwe-des dar oon des-kwen-to"},
            {sp:"¡Qué extraño!", en:"How strange!", ph:"Ke eks-tra-nyo"},
        ],
        hard: [
            {sp:"Espero que todo se resuelva de la mejor manera posible", en:"I hope everything works out in the best way possible", ph:"Es-pe-ro ke to-do se re-swel-ba de la me-hor ma-ne-ra po-see-ble"},
            {sp:"¿Podrías explicarme cómo funciona?", en:"Could you explain to me how it works?", ph:"Po-dree-as eks-plee-car-me co-mo foon-syo-na"},
            {sp:"No merece la pena preocuparse por eso ahora", en:"It's not worth worrying about that now", ph:"No me-re-se la pe-na pre-o-coo-par-se por e-so a-o-ra"},
            {sp:"Tengo mucho que aprender de esta experiencia", en:"I have a lot to learn from this experience", ph:"Ten-go moo-cho ke a-pren-der de es-ta eks-pe-ryen-sya"},
            {sp:"Cuanto más practico, más aprendo", en:"The more I practise, the more I learn", ph:"Kwan-to mas prak-tee-co mas a-pren-do"},
            {sp:"Por mucho que lo intento, no consigo dejar de pensar", en:"No matter how hard I try, I can't stop thinking", ph:"Por moo-cho ke lo een-ten-to no con-see-go de-har de pen-sar"},
            {sp:"La vida es mucho más que lo que vemos", en:"Life is much more than what we see", ph:"La bee-da es moo-cho mas ke lo ke be-mos"},
            {sp:"Cada persona tiene una perspectiva diferente", en:"Every person has a different perspective", ph:"Ca-da per-so-na tye-ne oo-na pers-pek-tee-ba dee-fe-ren-te"},
            {sp:"Tardó, pero finalmente llegamos a un acuerdo", en:"It took a while, but we finally reached an agreement", ph:"Tar-do pe-ro fee-nal-men-te ye-ga-mos a oon a-kwer-do"},
            {sp:"¿Puedes imaginar cómo sería sin tecnología?", en:"Can you imagine what it would be like without technology?", ph:"Pwe-des ee-ma-hee-nar co-mo se-ree-a seen tek-no-lo-hee-a"},
            {sp:"Hay que tener paciencia para aprender un idioma", en:"You need to have patience to learn a language", ph:"Ay ke te-ner pa-syen-sya pa-ra a-pren-der oon ee-dyo-ma"},
            {sp:"Sin comunicación no hay relación", en:"Without communication there is no relationship", ph:"Seen co-moo-nee-ca-syon no ay re-la-syon"},
            // More hard phrases
            {sp:"No puedo creer lo rápido que pasa el tiempo", en:"I can't believe how fast time flies", ph:"No pwe-do kre-er lo ra-pee-do ke pa-sa el tyen-po"},
            {sp:"Me gustaría saber más sobre la cultura española", en:"I would like to know more about Spanish culture", ph:"Me goos-ta-ree-a sa-ber mas so-bre la kool-too-ra es-pa-nyo-la"},
            {sp:"No es exactamente lo que quería decir", en:"That's not exactly what I meant to say", ph:"No es ek-sak-ta-men-te lo ke ke-ree-a de-seer"},
            {sp:"Es más fácil decirlo que hacerlo", en:"It's easier said than done", ph:"Es mas fa-seel de-seer-lo ke a-ser-lo"},
            {sp:"A veces el silencio dice más que las palabras", en:"Sometimes silence says more than words", ph:"A be-ses el see-len-syo dee-se mas ke las pa-la-bras"},
        ],
        vhard: [
            {sp:"No hay mal que por bien no venga", en:"Every cloud has a silver lining", ph:"Proverb"},
            {sp:"A caballo regalado no le mires el diente", en:"Don't look a gift horse in the mouth", ph:"Proverb"},
            {sp:"Más vale tarde que nunca", en:"Better late than never", ph:"Mas ba-le tar-de ke noon-ca"},
            {sp:"En boca cerrada no entran moscas", en:"Silence is golden (lit: flies don't enter a closed mouth)", ph:"Proverb"},
            {sp:"Camarón que se duerme, se lo lleva la corriente", en:"You snooze you lose", ph:"Proverb"},
            {sp:"Al mal tiempo, buena cara", en:"Make the best of a bad situation", ph:"Proverb"},
            {sp:"Dime con quién andas y te diré quién eres", en:"You are known by the company you keep", ph:"Proverb"},
            {sp:"No por mucho madrugar amanece más temprano", en:"Haste doesn't make things happen sooner", ph:"Proverb"},
            {sp:"Más vale pájaro en mano que ciento volando", en:"A bird in the hand is worth two in the bush", ph:"Proverb"},
            {sp:"Ojos que no ven, corazón que no siente", en:"Out of sight, out of mind", ph:"Proverb"},
            {sp:"El que mucho abarca, poco aprieta", en:"Don't bite off more than you can chew", ph:"Proverb"},
            {sp:"A quien madruga, Dios le ayuda", en:"The early bird catches the worm", ph:"Proverb"},
            {sp:"Meter la pata", en:"To put your foot in it", ph:"Idiom"}, {sp:"Costar un ojo de la cara", en:"To cost an arm and a leg", ph:"Idiom"},
            {sp:"Estar en las nubes", en:"To have your head in the clouds", ph:"Idiom"}, {sp:"No hay mal que dure cien años", en:"This too shall pass", ph:"Proverb"},
            {sp:"Tirar la casa por la ventana", en:"To splash out/go all out", ph:"Idiom"}, {sp:"Dar en el clavo", en:"To hit the nail on the head", ph:"Idiom"},
        ]
    }
};